import type { ServiceEntry } from "./types";

const CATEGORY = "family-sponsorship";

export const FAMILY_SPONSORSHIP_SERVICES: ServiceEntry[] = [
  {
    slug: "spousal-sponsorship",
    categorySlug: CATEGORY,
    title: "Spousal Sponsorship",
    icon: "HeartHandshake",
    image: "/images/services/family-sponsorship_spousal-sponsorship.jpg",
    shortDescription: "Sponsoring a married spouse for Canadian permanent residence.",
    suitableFor: "Canadian citizens or permanent residents who want to sponsor their legally married spouse.",
    overview: [
      "Spousal sponsorship allows a Canadian citizen or permanent resident to sponsor their legally married spouse for permanent residence, whether the spouse currently lives inside or outside Canada.",
      "The application has two linked parts: the sponsor's undertaking to support their spouse, and the spouse's application for permanent residence. Both are assessed together.",
      "The central question IRCC asks is whether the relationship is genuine and was not entered into primarily to gain immigration status — so the quality and consistency of relationship evidence matters a great deal.",
    ],
    eligibility: [
      "A legal marriage recognized in the jurisdiction where it took place and in Canada",
      "The sponsor meeting Canadian citizenship or permanent residency requirements, age, and residency obligations",
      "The sponsor not being under a current sponsorship bar or ineligibility",
      "A genuine ongoing relationship, supported by evidence",
      "The spouse meeting admissibility requirements (criminal, medical, security)",
    ],
    process: [
      { title: "Initial Assessment", text: "We review the sponsor's eligibility and the relationship history together." },
      { title: "Relationship Evidence Review", text: "We identify the strongest available evidence of a genuine relationship for your specific history." },
      { title: "Document Preparation", text: "Sponsor and applicant forms, photos, and supporting letters are compiled." },
      { title: "Application Submission", text: "The complete package is submitted, choosing inland or outland processing based on your circumstances." },
      { title: "Government Processing", text: "IRCC reviews both the sponsor's eligibility and the relationship; timelines vary by processing stream." },
      { title: "Additional Requests or Interview", text: "We help prepare for any request for more evidence or an interview, if one is scheduled." },
      { title: "Decision", text: "Once approved, the spouse receives permanent resident status." },
    ],
    documents: [
      "Marriage certificate",
      "Photos together spanning the relationship",
      "Evidence of ongoing communication",
      "Evidence of shared finances or a shared household, where applicable",
      "Sponsor's proof of status and income, where relevant",
      "Police certificates and medical exam results for the applicant",
    ],
    commonIssues: [
      "Relationship evidence that is thin, inconsistent, or recently assembled only for the application",
      "Missing documentation of the relationship's history and development over time",
      "Sponsor eligibility issues that aren't identified before applying",
      "Inconsistent information between the sponsor's and applicant's forms",
    ],
    howWeHelp: [
      "Assess sponsor eligibility honestly before you commit time to the application",
      "Advise on what relationship evidence will actually carry weight for your specific history",
      "Prepare a consistent, complete application for both sponsor and applicant",
      "Help prepare for any interview or additional evidence request",
    ],
    faq: [
      { question: "Can I sponsor my spouse if they're currently in Canada without status?", answer: "This depends heavily on the specific circumstances and current policy — it needs individual assessment rather than a general answer." },
      { question: "How long does spousal sponsorship take?", answer: "Processing times vary and change over time; we check current IRCC figures before setting expectations for your file." },
      { question: "Can my spouse work in Canada while the application is processing?", answer: "In some cases an open work permit can be applied for alongside the sponsorship application, depending on current policy and your spouse's location." },
      { question: "What if we don't have much documentation of our relationship?", answer: "We work with what's genuinely available and advise on building a credible picture going forward — fabricating evidence is never something we'd do or support." },
      { question: "What happens if the application is refused?", answer: "Depending on the reasons, it may be possible to appeal or to address the concerns and reapply — we review refusal letters carefully before advising on next steps." },
    ],
    relatedSlugs: ["family-sponsorship/common-law-partner-sponsorship", "temporary-residence/spousal-open-work-permit", "citizenship/canadian-citizenship"],
    seoTitle: "Spousal Sponsorship Applications",
    seoDescription: "Guidance on spousal sponsorship applications for Canadian citizens and permanent residents sponsoring their married spouse.",
  },
  {
    slug: "common-law-partner-sponsorship",
    categorySlug: CATEGORY,
    title: "Common-Law Partner Sponsorship",
    icon: "Users",
    image: "/images/services/family-sponsorship_common-law-partner-sponsorship.jpg",
    shortDescription: "Sponsoring a common-law partner for Canadian permanent residence.",
    suitableFor: "Canadian citizens or permanent residents in a genuine common-law relationship who want to sponsor their partner.",
    overview: [
      "Common-law partner sponsorship follows a very similar process to spousal sponsorship, but applies where the couple isn't legally married and instead has lived together continuously for the required period.",
      "Because there's no marriage certificate to establish the relationship, demonstrating cohabitation and a genuine shared life becomes central to the application.",
    ],
    eligibility: [
      "Continuous cohabitation with your partner for at least the required minimum period",
      "The sponsor meeting Canadian citizenship or permanent residency, age, and residency requirements",
      "A genuine relationship, supported by evidence of a shared life",
      "The partner meeting admissibility requirements (criminal, medical, security)",
    ],
    process: [
      { title: "Cohabitation Assessment", text: "We review your living history together against the minimum cohabitation requirement." },
      { title: "Evidence Review", text: "We identify documents that best show a shared household and finances over that period." },
      { title: "Document Preparation", text: "Sponsor and applicant forms, a cohabitation statement, and supporting letters are compiled." },
      { title: "Application Submission", text: "The complete package is submitted through the appropriate processing stream." },
      { title: "Government Processing", text: "IRCC reviews the cohabitation evidence and sponsor eligibility together." },
      { title: "Decision", text: "Once approved, the partner receives permanent resident status." },
    ],
    documents: [
      "Proof of shared address over the cohabitation period (leases, utility bills)",
      "Joint bank accounts or shared financial responsibilities",
      "Photos and evidence of the relationship over time",
      "Signed statutory declarations of common-law union",
      "Police certificates and medical exam results for the applicant",
    ],
    commonIssues: [
      "Gaps in proof of a shared address during the required cohabitation period",
      "Finances that remain entirely separate, raising questions about a shared life",
      "Confusing a common-law relationship's requirements with those for marriage",
      "Incomplete statutory declarations",
    ],
    howWeHelp: [
      "Confirm your cohabitation history actually meets the minimum period required",
      "Advise on practical ways to document a shared household going forward, if evidence is currently thin",
      "Prepare a complete, consistent application package",
      "Guide you through statutory declarations correctly",
    ],
    faq: [
      { question: "How long do we need to have lived together?", answer: "There's a minimum continuous cohabitation period required, which we confirm against current requirements for your situation." },
      { question: "Can short periods apart affect our application?", answer: "Brief, explainable separations (for work or family reasons) don't necessarily break cohabitation, but they should be documented and explained." },
      { question: "Do we need a lease in both names?", answer: "It helps, but isn't strictly required — a range of evidence can be used together to show a shared household." },
    ],
    relatedSlugs: ["family-sponsorship/spousal-sponsorship", "temporary-residence/spousal-open-work-permit"],
    seoTitle: "Common-Law Partner Sponsorship Applications",
    seoDescription: "Guidance on common-law partner sponsorship applications for Canadian citizens and permanent residents.",
  },
  {
    slug: "dependent-child-sponsorship",
    categorySlug: CATEGORY,
    title: "Dependent Child Sponsorship",
    icon: "Baby",
    image: "/images/services/family-sponsorship_dependent-child-sponsorship.jpg",
    shortDescription: "Sponsoring a dependent child for Canadian permanent residence.",
    suitableFor: "Canadian citizens or permanent residents who want to sponsor their dependent child.",
    overview: [
      "Dependent child sponsorship allows a Canadian citizen or permanent resident to sponsor their child for permanent residence, based on the child meeting the current definition of a dependant — generally tied to age and, in some cases, continuous enrollment in school.",
      "This is often done alongside a parent's own permanent residence or sponsorship application, but can also be a standalone sponsorship.",
    ],
    eligibility: [
      "The child meeting the current definition of a dependent child (age and, where relevant, study status)",
      "A legal parent-child relationship, through birth or adoption",
      "The sponsor meeting Canadian citizenship or permanent residency and sponsorship eligibility requirements",
      "The child meeting admissibility requirements (criminal, medical, security)",
    ],
    process: [
      { title: "Dependant Status Review", text: "We confirm the child currently meets the definition of a dependent child under IRCC rules." },
      { title: "Relationship Documentation", text: "Birth certificates or adoption records are organized to confirm the parent-child relationship." },
      { title: "Document Preparation", text: "Sponsor and application forms are prepared, along with any required custody documentation." },
      { title: "Application Submission", text: "The complete sponsorship package is submitted." },
      { title: "Government Processing", text: "IRCC reviews the relationship and admissibility of the child." },
      { title: "Decision", text: "Once approved, the child receives permanent resident status." },
    ],
    documents: [
      "Child's birth certificate or adoption documentation",
      "Custody documentation, where one parent is not involved in the application",
      "Sponsor's proof of citizenship or permanent residency",
      "Police certificates, where applicable by age",
      "Medical exam results",
    ],
    commonIssues: [
      "Assuming a child qualifies as a dependant without checking the current age and study-status definition",
      "Missing custody documentation in separated or blended family situations",
      "Incomplete relationship evidence for adopted children",
    ],
    howWeHelp: [
      "Confirm the child's dependant status against current IRCC criteria",
      "Advise on custody documentation needed for your specific family situation",
      "Prepare a complete and accurate sponsorship application",
    ],
    faq: [
      { question: "What is the current age limit for a dependent child?", answer: "This is set by IRCC policy and has changed over time, so we confirm the current definition rather than relying on an outdated figure." },
      { question: "Can I sponsor a stepchild?", answer: "This depends on the legal relationship and current IRCC definitions — we assess this individually." },
      { question: "Can I sponsor my child at the same time as my spouse?", answer: "Yes, in many cases a dependent child can be included in a spousal or common-law sponsorship application." },
    ],
    relatedSlugs: ["family-sponsorship/spousal-sponsorship", "family-sponsorship/parents-grandparents-sponsorship"],
    seoTitle: "Dependent Child Sponsorship Applications",
    seoDescription: "Guidance on dependent child sponsorship applications for Canadian citizens and permanent residents.",
  },
  {
    slug: "parents-grandparents-sponsorship",
    categorySlug: CATEGORY,
    title: "Parents & Grandparents Sponsorship",
    icon: "Home",
    image: "/images/services/family-sponsorship_parents-grandparents-sponsorship.jpg",
    shortDescription: "Sponsoring parents or grandparents for Canadian permanent residence.",
    suitableFor: "Canadian citizens or permanent residents who want their parents or grandparents to immigrate permanently.",
    overview: [
      "The Parents and Grandparents Program (PGP) allows Canadian citizens and permanent residents to sponsor their parents or grandparents for permanent residence.",
      "Because demand regularly exceeds the number of spots available, IRCC has in different years used methods such as a lottery-style invitation process to manage intake — so timing and process can change from year to year.",
      "Where the PGP isn't currently open or a fit, the Super Visa is often discussed as a complementary option for extended visits in the meantime.",
    ],
    eligibility: [
      "A parent or grandparent relationship to the sponsor",
      "The sponsor meeting income requirements over a specified period, in addition to citizenship/residency and age requirements",
      "Being invited to apply, where intake is managed through an interest-to-sponsor or lottery process",
      "The parent or grandparent meeting admissibility requirements",
    ],
    process: [
      { title: "Income & Eligibility Review", text: "We review the sponsor's income history against the current PGP threshold." },
      { title: "Interest to Sponsor / Intake", text: "Where required, we help submit an interest form or profile for the current intake process." },
      { title: "Invitation to Apply", text: "If invited, we prepare the full sponsorship application within the deadline." },
      { title: "Document Preparation", text: "Relationship, income, and admissibility documents are compiled." },
      { title: "Application Submission", text: "The complete package is submitted to IRCC." },
      { title: "Government Processing", text: "IRCC processes the application; timelines are generally longer for this category." },
    ],
    documents: [
      "Proof of relationship (birth certificates)",
      "Sponsor's Notices of Assessment for the required income period",
      "Proof of Canadian citizenship or permanent residency",
      "Police certificates and medical exam results for the applicant",
    ],
    commonIssues: [
      "Income that falls short of the required threshold for the relevant years",
      "Missing an intake window because the process is only open periodically",
      "Incomplete income documentation across the full required period",
    ],
    howWeHelp: [
      "Review income eligibility honestly before you commit to the process",
      "Track current intake announcements so you don't miss a window",
      "Prepare a complete, well-organized sponsorship application",
      "Discuss the Super Visa as an interim option where appropriate",
    ],
    faq: [
      { question: "Is the Parents and Grandparents Program always open for new applications?", answer: "No — intake has historically been managed in limited periods or through an invitation process, so timing depends on current IRCC announcements." },
      { question: "What income does the sponsor need?", answer: "A minimum income threshold applies, assessed over a specified number of recent tax years, which we check against current published figures." },
      { question: "What can we do if the PGP isn't currently open?", answer: "The Super Visa is often considered as a way to spend extended time together while waiting for a future PGP intake." },
    ],
    relatedSlugs: ["temporary-residence/super-visa", "family-sponsorship/spousal-sponsorship"],
    seoTitle: "Parents and Grandparents Sponsorship (PGP)",
    seoDescription: "Guidance on Parents and Grandparents Program sponsorship for Canadian citizens and permanent residents.",
  },
];
