import type { ServiceEntry } from "./types";

const CATEGORY = "irb-representation";

export const IRB_REPRESENTATION_SERVICES: ServiceEntry[] = [
  {
    slug: "refugee-claims",
    categorySlug: CATEGORY,
    title: "Refugee Claims",
    icon: "ShieldCheck",
    image: "/images/services/irb-representation_refugee-claims.jpg",
    shortDescription: "Representation for refugee protection claims before the Refugee Protection Division.",
    suitableFor: "People seeking protection in Canada because they fear persecution or serious harm in their home country.",
    overview: [
      "A refugee claim asks Canada to recognize that a person needs protection because they face persecution, or a risk to life or of cruel treatment, in their home country.",
      "Claims are heard by the Refugee Protection Division (RPD) of the Immigration and Refugee Board, and the strength of a claim depends heavily on a clear, consistent account supported by available evidence.",
      "This is a serious legal process with real consequences, so careful preparation and honest, thorough representation matter throughout.",
    ],
    eligibility: [
      "A well-founded fear of persecution based on a protected ground, or a personalized risk to life or of cruel treatment",
      "Eligibility to make a claim under Canadian immigration law (not everyone is eligible to claim, depending on prior immigration history)",
      "Filing the claim within required timelines once in Canada",
      "Providing a Basis of Claim form with a consistent, detailed account",
    ],
    process: [
      { title: "Initial Assessment", text: "We listen carefully to your situation and assess whether a claim is appropriate and what it would need to show." },
      { title: "Eligibility Determination", text: "An eligibility interview confirms whether your claim can proceed to the Refugee Protection Division." },
      { title: "Basis of Claim Preparation", text: "We help you prepare a clear, detailed, and consistent Basis of Claim form." },
      { title: "Evidence Gathering", text: "Supporting documents, country condition evidence, and any corroborating materials are organized." },
      { title: "Hearing Preparation", text: "We prepare you thoroughly for the hearing, including likely questions and how to present your account." },
      { title: "RPD Hearing", text: "We represent you at the hearing before the Refugee Protection Division." },
      { title: "Decision", text: "The RPD issues a decision; we explain what it means and the available next steps either way." },
    ],
    documents: [
      "Basis of Claim form",
      "Identity documents, where available",
      "Any evidence supporting the events described (police reports, medical records, news articles)",
      "Country condition documentation relevant to the claim",
      "Witness statements, where applicable",
    ],
    commonIssues: [
      "Inconsistencies between the Basis of Claim form and oral testimony",
      "Missing supporting evidence that could reasonably have been obtained",
      "Submitting the Basis of Claim without enough detail or clarity",
      "Not understanding what the hearing will involve and arriving unprepared",
    ],
    howWeHelp: [
      "Listen to your account carefully and help you present it clearly and consistently",
      "Identify what supporting evidence would genuinely strengthen the claim",
      "Prepare a thorough, well-organized Basis of Claim form",
      "Represent you at the hearing and prepare you for what to expect",
    ],
    faq: [
      { question: "Can anyone make a refugee claim in Canada?", answer: "Not everyone is eligible — prior immigration history and other factors can affect eligibility, which we assess at the outset." },
      { question: "What happens if my claim is accepted?", answer: "An accepted claim generally leads to protected person status, which can later support a permanent residence application." },
      { question: "What if my claim is refused?", answer: "Depending on the circumstances, there may be options such as an appeal to the Refugee Appeal Division or judicial review — we review refusal decisions carefully." },
      { question: "Do I need to speak English or French at my hearing?", answer: "No — interpretation is available, and we coordinate this as part of hearing preparation." },
    ],
    relatedSlugs: ["irb-representation/admissibility-hearings", "irb-representation/sponsorship-appeals", "other-immigration-services/humanitarian-compassionate-applications"],
    seoTitle: "Refugee Claim Representation",
    seoDescription: "Representation for refugee protection claims before the Refugee Protection Division, including hearing preparation.",
  },
  {
    slug: "admissibility-hearings",
    categorySlug: CATEGORY,
    title: "Admissibility Hearings",
    icon: "Gavel",
    image: "/images/services/irb-representation_admissibility-hearings.jpg",
    shortDescription: "Representation at admissibility hearings before the Immigration Division.",
    suitableFor: "People facing an admissibility hearing over alleged grounds of inadmissibility to Canada.",
    overview: [
      "An admissibility hearing before the Immigration Division (ID) decides whether a person is inadmissible to Canada on specific grounds raised by the Canada Border Services Agency (CBSA) or IRCC — such as criminality, misrepresentation, or other statutory grounds.",
      "The outcome can affect a person's ability to remain in or enter Canada, so understanding the specific allegation and responding to it properly is essential.",
    ],
    eligibility: [
      "Having received a report alleging inadmissibility that has been referred to the Immigration Division",
      "A hearing date scheduled by the ID",
      "The right to be represented at the hearing",
    ],
    process: [
      { title: "Report Review", text: "We review the inadmissibility report and allegation in detail to understand exactly what's being claimed." },
      { title: "Evidence Assessment", text: "We identify what evidence and legal arguments are available to respond to the allegation." },
      { title: "Hearing Preparation", text: "We prepare submissions and prepare you for what the hearing will involve." },
      { title: "ID Hearing", text: "We represent you at the hearing before the Immigration Division." },
      { title: "Decision", text: "The ID issues a decision; we explain the outcome and any further options." },
    ],
    documents: [
      "The inadmissibility report and referral documents",
      "Identity and immigration status documents",
      "Any evidence relevant to the specific allegation",
      "Legal submissions prepared for the hearing",
    ],
    commonIssues: [
      "Not fully understanding the specific ground of inadmissibility alleged",
      "Missing the opportunity to gather evidence before the hearing date",
      "Attending without representation when the stakes are significant",
    ],
    howWeHelp: [
      "Explain clearly what the specific allegation means for your situation",
      "Identify and gather evidence relevant to responding to it",
      "Prepare thorough submissions for the hearing",
      "Represent you directly before the Immigration Division",
    ],
    faq: [
      { question: "What happens if I'm found inadmissible?", answer: "Consequences depend on the ground and your specific status — this can include a removal order, which we would review for any further options." },
      { question: "Can I bring evidence to the hearing?", answer: "Yes, and preparing that evidence properly in advance is a central part of hearing preparation." },
      { question: "How much notice do I get before a hearing?", answer: "This varies by case — we act quickly once retained to make the most of the time available." },
    ],
    relatedSlugs: ["irb-representation/detention-reviews", "irb-representation/sponsorship-appeals"],
    seoTitle: "Admissibility Hearing Representation",
    seoDescription: "Representation at admissibility hearings before the Immigration Division of the Immigration and Refugee Board.",
  },
  {
    slug: "detention-reviews",
    categorySlug: CATEGORY,
    title: "Detention Reviews",
    icon: "Scale",
    image: "/images/services/irb-representation_detention-reviews.jpg",
    shortDescription: "Representation at immigration detention review hearings.",
    suitableFor: "People detained under immigration law, or their family, seeking representation at a detention review.",
    overview: [
      "When a person is detained under immigration law, the Immigration Division holds detention reviews to decide whether continued detention is justified, or whether the person should be released, often subject to conditions.",
      "These hearings happen on a set schedule and move quickly, so prompt, well-prepared representation can make a meaningful difference to the outcome.",
    ],
    eligibility: [
      "Being currently detained under immigration law",
      "A scheduled detention review before the Immigration Division",
      "The right to be represented, and in some cases to propose a bondsperson",
    ],
    process: [
      { title: "Urgent Case Review", text: "We review the circumstances of detention quickly, given the time-sensitive nature of these hearings." },
      { title: "Release Plan Preparation", text: "Where appropriate, we help identify a bondsperson and a release plan addressing the board's concerns." },
      { title: "Evidence Gathering", text: "We gather identity, community ties, and other relevant evidence to support the review." },
      { title: "Detention Review Hearing", text: "We represent you at the hearing before the Immigration Division." },
      { title: "Decision & Next Steps", text: "We explain the outcome and what happens at the next scheduled review, if detention continues." },
    ],
    documents: [
      "Identity documents, where available",
      "Proposed bondsperson's documentation and proof of ties",
      "Evidence of community ties, housing, or an address for release",
      "Any relevant immigration or criminal history documentation",
    ],
    commonIssues: [
      "Not having a bondsperson or release plan ready before the review",
      "Limited time to prepare, given how quickly these hearings are scheduled",
      "Incomplete documentation of community ties or an address",
    ],
    howWeHelp: [
      "Act quickly given the short timelines involved in detention matters",
      "Help identify and prepare a bondsperson where appropriate",
      "Present a clear release plan addressing the board's likely concerns",
      "Represent you at each scheduled review",
    ],
    faq: [
      { question: "How often are detention reviews held?", answer: "They're held on a set schedule set by law, with the first review shortly after detention begins and further reviews afterward." },
      { question: "What is a bondsperson?", answer: "A bondsperson is someone who agrees to supervise and support the detained person if released, sometimes with a financial deposit or guarantee." },
      { question: "Can detention end with conditions instead of full release?", answer: "Yes, release is often subject to conditions such as reporting requirements or a deposit, decided based on the specific case." },
    ],
    relatedSlugs: ["irb-representation/admissibility-hearings", "irb-representation/refugee-claims"],
    seoTitle: "Detention Review Representation",
    seoDescription: "Representation at immigration detention review hearings before the Immigration Division.",
  },
  {
    slug: "sponsorship-appeals",
    categorySlug: CATEGORY,
    title: "Sponsorship Appeals",
    icon: "FileWarning",
    image: "/images/services/irb-representation_sponsorship-appeals.jpg",
    shortDescription: "Appealing a refused family sponsorship application to the Immigration Appeal Division.",
    suitableFor: "Sponsors whose family sponsorship application was refused and who want to appeal the decision.",
    overview: [
      "When a family sponsorship application is refused, the sponsor generally has the right to appeal to the Immigration Appeal Division (IAD), which independently reviews the refusal.",
      "An appeal can address both legal errors in the original decision and, in many cases, new evidence or humanitarian and compassionate factors not fully considered before.",
    ],
    eligibility: [
      "Being the sponsor of a refused sponsorship application with a right of appeal",
      "Filing the appeal within the strict deadline after receiving the refusal",
      "A genuine basis to challenge the refusal, whether legal, factual, or humanitarian",
    ],
    process: [
      { title: "Refusal Letter Review", text: "We review the refusal letter and visa office notes in detail to understand the exact reasons." },
      { title: "Appeal Filing", text: "The notice of appeal is filed with the Immigration Appeal Division within the required deadline." },
      { title: "Evidence & Submissions", text: "We gather additional evidence and prepare written submissions addressing the refusal's specific concerns." },
      { title: "Hearing Preparation", text: "We prepare you and any witnesses for the appeal hearing." },
      { title: "IAD Hearing", text: "We represent you at the hearing before the Immigration Appeal Division." },
      { title: "Decision", text: "The IAD issues a decision; we explain what it means and any further options." },
    ],
    documents: [
      "The original refusal letter and visa office notes (GCMS notes)",
      "Any new evidence addressing the refusal's specific concerns",
      "Updated relationship or sponsor eligibility evidence",
      "Written submissions prepared for the appeal",
    ],
    commonIssues: [
      "Missing the strict appeal filing deadline after a refusal",
      "Appealing without first understanding exactly why the application was refused",
      "Submitting an appeal with no new evidence or argument addressing the refusal's concerns",
    ],
    howWeHelp: [
      "Review the refusal and underlying officer's notes carefully before deciding on an appeal strategy",
      "File the appeal promptly, within the required deadline",
      "Gather evidence and submissions that directly respond to the refusal's reasons",
      "Represent you at the appeal hearing",
    ],
    faq: [
      { question: "How long do I have to file an appeal?", answer: "There's a strict deadline after receiving a refusal, so it's important to contact us as soon as possible after a refusal letter arrives." },
      { question: "Can I submit new evidence that wasn't in the original application?", answer: "In many cases yes, particularly evidence addressing the specific reasons for refusal, though rules around this can be technical." },
      { question: "What if the appeal is also unsuccessful?", answer: "Depending on the outcome, there may be further options such as judicial review, which we would discuss based on the specific decision." },
    ],
    relatedSlugs: ["family-sponsorship/spousal-sponsorship", "other-immigration-services/procedural-fairness-letter-responses"],
    seoTitle: "Sponsorship Appeal Representation",
    seoDescription: "Representation for family sponsorship appeals before the Immigration Appeal Division.",
  },
];
