import type { ServiceEntry } from "./types";

const CATEGORY = "other-immigration-services";

export const OTHER_SERVICES: ServiceEntry[] = [
  {
    slug: "business-immigration",
    categorySlug: CATEGORY,
    title: "Business Immigration",
    icon: "Building2",
    image: "/images/services/other-immigration-services_business-immigration.jpg",
    shortDescription: "Pathways for entrepreneurs, investors, and self-employed applicants.",
    suitableFor: "Entrepreneurs, investors, and self-employed people exploring business-based immigration to Canada.",
    overview: [
      "Business immigration covers a range of pathways for people who want to immigrate to Canada by starting, buying, or investing in a business, or through self-employment in certain fields.",
      "These pathways vary considerably — some run at the provincial level with their own net worth and investment requirements, others are federal. The right fit depends entirely on your business background, available capital, and goals.",
    ],
    eligibility: [
      "Relevant business ownership, management, or self-employment experience",
      "Meeting the specific program's net worth or investment requirements, where applicable",
      "A viable business plan appropriate to the chosen pathway",
      "Language and other general admissibility requirements",
    ],
    process: [
      { title: "Business Profile Assessment", text: "We review your business background, capital, and goals against available pathways." },
      { title: "Pathway Identification", text: "We identify which provincial or federal business stream currently fits your profile." },
      { title: "Business Plan Preparation", text: "A business plan is prepared or refined to meet the chosen program's requirements." },
      { title: "Application Preparation", text: "The application is prepared with financial, business, and identity documentation." },
      { title: "Submission", text: "The application is submitted to the relevant provincial or federal authority." },
      { title: "Government Processing", text: "The application is reviewed; timelines vary significantly by program." },
    ],
    documents: [
      "Business ownership and management evidence",
      "Net worth and source-of-funds documentation",
      "Business plan",
      "Financial statements or tax records",
      "Identity and language documents",
    ],
    commonIssues: [
      "Choosing a program that doesn't actually match your business background or capital",
      "Source-of-funds documentation that isn't clearly traceable",
      "A business plan that doesn't meet the specific program's requirements",
    ],
    howWeHelp: [
      "Assess your business background honestly against available pathways",
      "Help prepare a business plan suited to the specific program",
      "Organize financial and source-of-funds documentation clearly",
      "Prepare and submit a complete application",
    ],
    faq: [
      { question: "Do I need a minimum net worth to qualify?", answer: "Many business immigration streams set a minimum net worth or investment amount, which varies by program and province." },
      { question: "Can I apply for a business program without ever having run a business?", answer: "Most programs require relevant business or management experience, so this needs to be assessed against the specific program's criteria." },
      { question: "How long do business immigration programs take?", answer: "Timelines vary widely by program, often including a conditional period tied to establishing the business in Canada." },
    ],
    relatedSlugs: ["permanent-residence/provincial-nominee-program", "temporary-residence/lmia"],
    seoTitle: "Business Immigration Guidance",
    seoDescription: "Guidance on business immigration pathways for entrepreneurs, investors, and self-employed applicants.",
  },
  {
    slug: "humanitarian-compassionate-applications",
    categorySlug: CATEGORY,
    title: "Humanitarian & Compassionate Applications",
    icon: "Heart",
    image: "/images/services/other-immigration-services_humanitarian-compassionate-applications.jpg",
    shortDescription: "Requests for an exception to normal immigration requirements based on compelling personal circumstances.",
    suitableFor: "People facing compelling personal circumstances who don't qualify under a standard immigration category.",
    overview: [
      "A Humanitarian and Compassionate (H&C) application asks IRCC to make an exception to normal immigration requirements because of compelling circumstances — such as a person's establishment in Canada, hardship if they had to leave, or the best interests of a child involved.",
      "This is a discretionary application, decided case by case rather than against a fixed checklist, so a clear, well-documented personal story matters a great deal.",
    ],
    eligibility: [
      "Compelling personal circumstances that go beyond normal hardship",
      "No existing legal pathway reasonably available to address the situation",
      "Evidence supporting the specific grounds raised (establishment, hardship, best interests of a child, or others)",
    ],
    process: [
      { title: "Circumstance Assessment", text: "We listen to your full situation and assess whether an H&C application is realistically appropriate." },
      { title: "Evidence Identification", text: "We identify what evidence would best support the specific grounds in your case." },
      { title: "Submissions Preparation", text: "A detailed written submission is prepared explaining your circumstances and supporting evidence." },
      { title: "Application Submission", text: "The complete H&C application is submitted to IRCC." },
      { title: "Government Processing", text: "IRCC reviews the application on a discretionary basis; processing times can be lengthy." },
      { title: "Decision", text: "We explain the decision and, where relevant, next steps either way." },
    ],
    documents: [
      "Evidence of establishment in Canada (employment, community ties, length of residence)",
      "Evidence relevant to hardship if required to leave Canada",
      "Evidence relevant to the best interests of any child affected",
      "Supporting letters and personal statements",
    ],
    commonIssues: [
      "Submitting generic hardship claims without specific, personal supporting evidence",
      "Not addressing the best interests of a child clearly, where children are involved",
      "Treating H&C as a quick alternative when no compelling circumstances actually exist",
    ],
    howWeHelp: [
      "Give an honest assessment of whether H&C is realistically suited to your situation",
      "Help identify and gather the evidence that matters most for your specific grounds",
      "Prepare thorough, well-organized written submissions",
      "Explain realistic timelines and outcomes throughout",
    ],
    faq: [
      { question: "Is H&C a guaranteed way to stay in Canada?", answer: "No — it's a discretionary request, assessed individually, and there's no guarantee of a particular outcome." },
      { question: "How long does an H&C application take?", answer: "Processing times can be considerably longer than standard applications, and vary by case complexity and volume." },
      { question: "Can I include my children in an H&C application?", answer: "Yes, and the best interests of any child affected are specifically considered as part of the assessment." },
    ],
    relatedSlugs: ["irb-representation/refugee-claims", "other-immigration-services/restoration-of-status"],
    seoTitle: "Humanitarian & Compassionate Application Support",
    seoDescription: "Support with Humanitarian and Compassionate applications requesting an exception to standard immigration requirements.",
  },
  {
    slug: "visitor-record-status-extension",
    categorySlug: CATEGORY,
    title: "Visitor Record / Status Extension",
    icon: "Clock",
    image: "/images/services/other-immigration-services_visitor-record-status-extension.jpg",
    shortDescription: "Extending your authorized stay in Canada as a visitor.",
    suitableFor: "Visitors currently in Canada who want to extend their authorized stay before it expires.",
    overview: [
      "A visitor record extends a person's authorized stay in Canada as a visitor, applied for before the current authorization expires.",
      "Approval depends on showing a genuine continuing reason for the extended visit and that you still meet the general requirements of a temporary resident.",
    ],
    eligibility: [
      "Current valid temporary resident status in Canada",
      "A genuine reason for extending the stay",
      "Continued ties to your home country and intent to leave at the end of the authorized period",
      "No criminal or medical inadmissibility concerns",
    ],
    process: [
      { title: "Status Review", text: "We confirm your current status and the deadline for applying to extend it." },
      { title: "Reason & Evidence Review", text: "We identify the strongest way to present your reason for extending your stay." },
      { title: "Application Preparation", text: "The visitor record application is prepared with supporting documents." },
      { title: "Submission", text: "The application is submitted before your current status expires, where possible." },
      { title: "Government Processing", text: "IRCC processes the extension; you generally maintain status while it's pending if applied for before expiry." },
      { title: "Decision", text: "Once approved, you receive a new visitor record with an updated authorized stay." },
    ],
    documents: [
      "Valid passport and current visitor record or entry stamp",
      "Proof of funds for the extended stay",
      "Evidence supporting the reason for extension",
      "Evidence of ties to your home country",
    ],
    commonIssues: [
      "Applying too close to, or after, the current authorized stay expires",
      "A vague or unsupported reason for the extension",
      "Insufficient proof of funds for the additional time requested",
    ],
    howWeHelp: [
      "Track your status expiry and timing for the extension application",
      "Help present a clear, credible reason for the extended stay",
      "Prepare a complete application with supporting evidence",
    ],
    faq: [
      { question: "Can I stay in Canada while my extension is being processed?", answer: "If you apply before your current status expires, you generally have maintained status while IRCC processes the request." },
      { question: "What if my extension is refused after my original status expired?", answer: "This needs individual review — we would discuss your options promptly given the time-sensitive nature of the situation." },
      { question: "Is there a limit to how many times I can extend?", answer: "There's no fixed limit, but each extension is assessed on its own merits, and a pattern of extensions can draw more scrutiny." },
    ],
    relatedSlugs: ["temporary-residence/visitor-visa", "other-immigration-services/restoration-of-status"],
    seoTitle: "Visitor Record & Status Extension Support",
    seoDescription: "Support extending authorized visitor status in Canada through a visitor record application.",
  },
  {
    slug: "pr-card-renewal",
    categorySlug: CATEGORY,
    title: "PR Card Renewal",
    icon: "RefreshCw",
    image: "/images/services/other-immigration-services_pr-card-renewal.jpg",
    shortDescription: "Renewing an expiring or expired Permanent Resident Card.",
    suitableFor: "Permanent residents whose PR card is expiring or has expired.",
    overview: [
      "A Permanent Resident (PR) Card is the official proof of permanent resident status needed to re-enter Canada by commercial transportation, and it needs periodic renewal.",
      "Renewal depends on meeting the residency obligation — generally time physically present in Canada over a set period — which we review carefully before applying.",
    ],
    eligibility: [
      "Current permanent resident status that hasn't been lost or revoked",
      "Meeting the residency obligation over the relevant five-year period",
      "A valid reason and address in Canada for the card to be delivered to",
    ],
    process: [
      { title: "Residency Obligation Review", text: "We calculate your time in Canada over the relevant period to confirm you meet the residency obligation." },
      { title: "Document Preparation", text: "Travel history and identity documents are organized to support the renewal." },
      { title: "Application Submission", text: "The renewal application is submitted to IRCC." },
      { title: "Government Processing", text: "IRCC reviews the application and residency history." },
      { title: "Card Issuance", text: "Once approved, the new PR card is mailed to your Canadian address." },
    ],
    documents: [
      "Current or expired PR card",
      "Travel history for the residency obligation calculation",
      "Valid passport or other identity document",
      "Canadian mailing address",
    ],
    commonIssues: [
      "Falling short of the residency obligation due to extended time outside Canada",
      "Applying from outside Canada without understanding the different process that applies",
      "Incomplete or inconsistent travel history documentation",
    ],
    howWeHelp: [
      "Calculate your residency obligation accurately before you apply",
      "Advise on options if you're close to, or below, the requirement",
      "Prepare a complete and accurate renewal application",
    ],
    faq: [
      { question: "What happens if I don't meet the residency obligation?", answer: "This can affect your permanent resident status, so it's important to review your situation with us before applying or travelling further." },
      { question: "How do I renew my PR card if I'm outside Canada?", answer: "A different process applies for renewing or replacing a PR card from outside Canada, often involving a travel document instead — see our PR Travel Document service." },
      { question: "How long does PR card renewal take?", answer: "Processing times vary — we check current figures and help you plan around any travel needs." },
    ],
    relatedSlugs: ["other-immigration-services/pr-travel-document", "other-immigration-services/restoration-of-status"],
    seoTitle: "PR Card Renewal Assistance",
    seoDescription: "Assistance renewing an expiring or expired Permanent Resident Card, including residency obligation review.",
  },
  {
    slug: "pr-travel-document",
    categorySlug: CATEGORY,
    title: "Permanent Resident Travel Document",
    icon: "Stamp",
    image: "/images/services/other-immigration-services_pr-travel-document.jpg",
    shortDescription: "A travel document allowing a permanent resident outside Canada to return without a valid PR card.",
    suitableFor: "Permanent residents outside Canada who don't have a valid PR card and need to return.",
    overview: [
      "A Permanent Resident Travel Document (PRTD) allows a permanent resident outside Canada without a valid PR card to board a flight back to Canada.",
      "Like PR card renewal, approval depends on meeting the residency obligation, or on H&C factors where it hasn't been fully met — so this is often a more involved application than a routine renewal.",
    ],
    eligibility: [
      "Current permanent resident status",
      "Being outside Canada without a valid PR card",
      "Meeting the residency obligation, or presenting H&C factors where there's a shortfall",
    ],
    process: [
      { title: "Residency Obligation Review", text: "We assess your time in and outside Canada against the residency obligation." },
      { title: "Application Preparation", text: "The PRTD application is prepared with travel history and supporting documents." },
      { title: "H&C Submission, If Needed", text: "Where the residency obligation isn't fully met, we prepare H&C submissions addressing the shortfall." },
      { title: "Submission to a Visa Office", text: "The application is submitted to the relevant Canadian visa office abroad." },
      { title: "Government Processing & Interview", text: "An interview is often required; we help you prepare for it." },
      { title: "Decision", text: "Once approved, the travel document allows you to board your flight to Canada." },
    ],
    documents: [
      "Valid passport",
      "Proof of permanent resident status",
      "Travel history for the residency obligation calculation",
      "H&C evidence, where the residency obligation isn't fully met",
    ],
    commonIssues: [
      "A significant shortfall in the residency obligation without H&C evidence to address it",
      "Missing or inconsistent travel history records",
      "Not preparing adequately for the visa office interview",
    ],
    howWeHelp: [
      "Assess your residency obligation and realistic chances honestly before applying",
      "Prepare H&C submissions where there's a shortfall to address",
      "Help you prepare for the visa office interview",
    ],
    faq: [
      { question: "What if I don't meet the residency obligation at all?", answer: "A PRTD may still be considered based on humanitarian and compassionate factors, though approval isn't guaranteed — we assess this honestly case by case." },
      { question: "Is an interview always required?", answer: "Many PRTD applications involve an interview at the visa office, which we help you prepare for." },
      { question: "How long does this process take?", answer: "This varies by visa office and the complexity of your residency history — we set realistic expectations based on your specific case." },
    ],
    relatedSlugs: ["other-immigration-services/pr-card-renewal", "other-immigration-services/restoration-of-status"],
    seoTitle: "Permanent Resident Travel Document (PRTD) Support",
    seoDescription: "Support applying for a Permanent Resident Travel Document for permanent residents outside Canada without a valid PR card.",
  },
  {
    slug: "restoration-of-status",
    categorySlug: CATEGORY,
    title: "Restoration of Status",
    icon: "RefreshCw",
    image: "/images/services/other-immigration-services_restoration-of-status.jpg",
    shortDescription: "Restoring temporary resident status after it has recently expired.",
    suitableFor: "Visitors, students, or workers whose temporary status recently expired and who want to restore it.",
    overview: [
      "Restoration of status allows a person whose visitor, study, or work permit has recently expired to apply to restore it, within a limited window, rather than having to leave Canada and reapply from outside.",
      "This is time-sensitive — the restoration window is short, and acting quickly matters.",
    ],
    eligibility: [
      "Temporary resident status that expired within the current restoration window",
      "Meeting the original conditions of the status being restored",
      "No criminal or medical inadmissibility concerns",
      "Applying for restoration alongside, or before, any extension request",
    ],
    process: [
      { title: "Urgent Status Review", text: "We confirm how long ago your status expired and whether you're still within the restoration window." },
      { title: "Document Preparation", text: "Supporting documents for both restoration and any underlying extension are compiled quickly." },
      { title: "Application Submission", text: "The restoration application is submitted as soon as possible within the window." },
      { title: "Government Processing", text: "IRCC processes the restoration request along with any linked extension." },
      { title: "Decision", text: "Once approved, your status is restored as though it hadn't lapsed." },
    ],
    documents: [
      "Expired permit or visitor record",
      "Valid passport",
      "Evidence supporting continued eligibility for the status being restored",
      "Proof of funds, where relevant",
    ],
    commonIssues: [
      "Missing the restoration window because of a delay in seeking help",
      "Assuming restoration is automatic rather than a separate application",
      "Incomplete documentation for the underlying status being restored",
    ],
    howWeHelp: [
      "Act quickly to confirm whether you're still within the restoration window",
      "Prepare a complete restoration application without delay",
      "Coordinate the extension of the underlying status alongside restoration",
    ],
    faq: [
      { question: "How long do I have to apply for restoration?", answer: "There's a short window after status expires — we confirm the current deadline for your situation immediately, since timing is critical." },
      { question: "Can I work or study while my restoration is pending?", answer: "This depends on the type of status and specific permit conditions — we review this with you directly." },
      { question: "What happens if I miss the restoration window?", answer: "Once the window passes, restoration generally isn't available, and other options — such as leaving Canada and reapplying — would need to be considered." },
    ],
    relatedSlugs: ["other-immigration-services/visitor-record-status-extension", "other-immigration-services/temporary-resident-permit"],
    seoTitle: "Restoration of Status Assistance",
    seoDescription: "Assistance restoring temporary resident status in Canada shortly after a visitor, study, or work permit has expired.",
  },
  {
    slug: "temporary-resident-permit",
    categorySlug: CATEGORY,
    title: "Temporary Resident Permit",
    icon: "FileClock",
    image: "/images/services/other-immigration-services_temporary-resident-permit.jpg",
    shortDescription: "A permit allowing entry or stay in Canada despite an inadmissibility, where justified.",
    suitableFor: "People who are otherwise inadmissible to Canada but have a justified reason to enter or remain temporarily.",
    overview: [
      "A Temporary Resident Permit (TRP) can allow a person who is otherwise inadmissible to Canada — for example, due to a past criminal record — to enter or remain temporarily, where the need to be in Canada outweighs the risk.",
      "This is a discretionary decision balancing the reasons for the visit against the specific inadmissibility, so a clear, well-supported explanation is central to the application.",
    ],
    eligibility: [
      "A specific, identifiable ground of inadmissibility",
      "A justified, compelling reason for entering or remaining in Canada despite that inadmissibility",
      "Evidence that the need for entry outweighs the risk associated with the inadmissibility",
    ],
    process: [
      { title: "Inadmissibility Assessment", text: "We identify exactly which ground of inadmissibility applies to your situation." },
      { title: "Justification Review", text: "We help articulate a clear, specific reason for needing to enter or remain in Canada." },
      { title: "Document Preparation", text: "Supporting evidence addressing both the inadmissibility and the justification is organized." },
      { title: "Application Submission", text: "The TRP application is submitted to the relevant visa office or port of entry." },
      { title: "Government Processing", text: "The application is reviewed on a discretionary basis; timelines vary by office." },
      { title: "Decision", text: "If approved, the permit allows entry or stay for a specified period and purpose." },
    ],
    documents: [
      "Evidence and details of the specific inadmissibility",
      "Evidence supporting the reason for the visit or stay",
      "Identity documents",
      "Any relevant court or legal records tied to the inadmissibility",
    ],
    commonIssues: [
      "A justification that doesn't clearly outweigh the specific inadmissibility concern",
      "Missing documentation that fully explains the inadmissibility itself",
      "Applying without first confirming exactly which ground of inadmissibility applies",
    ],
    howWeHelp: [
      "Identify the precise ground of inadmissibility involved",
      "Help build a clear, credible justification for the permit",
      "Prepare a complete, well-supported application",
    ],
    faq: [
      { question: "Is a TRP a permanent solution?", answer: "No — it's a temporary, discretionary permit for a specific period and purpose, separate from any permanent resolution of an inadmissibility." },
      { question: "Can a TRP lead to permanent residence?", answer: "In some cases a TRP holder may later explore other options, but this depends heavily on the individual situation and would need separate assessment." },
      { question: "How is a TRP different from criminal rehabilitation?", answer: "Rehabilitation permanently resolves certain criminality-related inadmissibility, while a TRP is a temporary, discretionary permit — we discuss which applies to your situation." },
    ],
    relatedSlugs: ["other-immigration-services/restoration-of-status", "other-immigration-services/procedural-fairness-letter-responses"],
    seoTitle: "Temporary Resident Permit (TRP) Applications",
    seoDescription: "Support with Temporary Resident Permit applications for people who are otherwise inadmissible to Canada.",
  },
  {
    slug: "procedural-fairness-letter-responses",
    categorySlug: CATEGORY,
    title: "Procedural Fairness Letter Responses",
    icon: "FileWarning",
    image: "/images/services/other-immigration-services_procedural-fairness-letter-responses.jpg",
    shortDescription: "Responding to an IRCC letter raising concerns before a decision is made.",
    suitableFor: "Applicants who have received a procedural fairness letter raising a specific concern about their application.",
    overview: [
      "A procedural fairness letter (PFL) is sent when an immigration officer has a specific concern about an application — such as a suspicion of misrepresentation or missing information — and gives the applicant a chance to respond before a final decision is made.",
      "How this letter is responded to can directly determine the outcome of the application, so understanding exactly what's being asked and responding carefully and honestly is critical.",
    ],
    eligibility: [
      "Having received a procedural fairness letter from IRCC",
      "A response deadline set out in the letter",
      "A genuine, complete explanation available to address the specific concern raised",
    ],
    process: [
      { title: "Letter Review", text: "We review the procedural fairness letter carefully to understand precisely what concern has been raised." },
      { title: "Evidence Gathering", text: "We identify and gather evidence that directly addresses the officer's specific concern." },
      { title: "Response Drafting", text: "A clear, complete written response is drafted addressing each point raised." },
      { title: "Submission", text: "The response is submitted within the deadline set in the letter." },
      { title: "Government Review", text: "The officer reviews the response alongside the rest of the application." },
      { title: "Decision", text: "We explain the eventual decision and any further options." },
    ],
    documents: [
      "The procedural fairness letter itself",
      "Evidence directly addressing the specific concern raised",
      "Any original application documents that need clarification",
    ],
    commonIssues: [
      "Missing the response deadline set out in the letter",
      "A response that doesn't directly address the specific concern raised",
      "Providing new information that creates further inconsistencies",
    ],
    howWeHelp: [
      "Read the letter closely to identify exactly what's being asked",
      "Help gather the right evidence to respond to the specific concern",
      "Draft a clear, honest, and complete response within the deadline",
    ],
    faq: [
      { question: "What happens if I don't respond to a procedural fairness letter?", answer: "A decision may be made without your input, often unfavourably, so it's important to respond within the deadline given." },
      { question: "Does receiving this letter mean my application will be refused?", answer: "Not necessarily — it's an opportunity to address a concern before a final decision, and a clear response can resolve many of these letters." },
      { question: "How much time do I have to respond?", answer: "The letter itself sets out the deadline, which varies by case — contact us as soon as you receive one." },
    ],
    relatedSlugs: ["irb-representation/sponsorship-appeals", "other-immigration-services/gcms-notes"],
    seoTitle: "Procedural Fairness Letter Response Support",
    seoDescription: "Support responding to IRCC procedural fairness letters raising specific concerns about an application.",
  },
  {
    slug: "gcms-notes",
    categorySlug: CATEGORY,
    title: "GCMS Notes Requests",
    icon: "FileText",
    image: "/images/services/other-immigration-services_gcms-notes.jpg",
    shortDescription: "Requesting the detailed government case notes behind an immigration decision.",
    suitableFor: "Applicants who want to understand the detailed reasoning behind an IRCC decision on their file.",
    overview: [
      "GCMS notes are the detailed internal case notes IRCC officers keep on an application, and requesting them (through an Access to Information request) can reveal the specific reasoning behind a decision, especially a refusal.",
      "These notes are often the starting point for deciding whether to appeal, reapply, or pursue another option after a refusal.",
    ],
    eligibility: [
      "Being the applicant, or an authorized representative, on the file in question",
      "A completed Access to Information and Privacy (ATIP) request",
    ],
    process: [
      { title: "Request Preparation", text: "We prepare the Access to Information and Privacy (ATIP) request for your file." },
      { title: "Submission", text: "The request is submitted to IRCC's ATIP office." },
      { title: "Processing", text: "IRCC processes the request; timelines can be lengthy, especially for complex files." },
      { title: "Notes Review", text: "Once received, we review the GCMS notes with you and explain what they show." },
      { title: "Next Steps", text: "We discuss what the notes mean for an appeal, a fresh application, or another option." },
    ],
    documents: [
      "Identity documents confirming you are the applicant or authorized representative",
      "Completed ATIP request form",
      "Application or file reference number",
    ],
    commonIssues: [
      "Requesting notes without a clear plan for what to do with the information",
      "Not accounting for how long ATIP requests can take to process",
      "Missing the specific file or reference details needed for the request",
    ],
    howWeHelp: [
      "Prepare and submit a complete ATIP request",
      "Explain the GCMS notes in plain language once received",
      "Advise on next steps based on what the notes actually show",
    ],
    faq: [
      { question: "How long does it take to get GCMS notes?", answer: "Processing times vary and can be lengthy — we set realistic expectations based on current ATIP processing volumes." },
      { question: "Why would I need GCMS notes?", answer: "They're especially useful after a refusal, to understand the officer's specific reasoning before deciding on an appeal or a new application." },
      { question: "Can I request these notes myself?", answer: "Yes, but we often help prepare the request correctly and, more importantly, help interpret the notes once they arrive." },
    ],
    relatedSlugs: ["irb-representation/sponsorship-appeals", "other-immigration-services/procedural-fairness-letter-responses"],
    seoTitle: "GCMS Notes Request Support",
    seoDescription: "Support requesting and interpreting GCMS case notes behind an IRCC immigration decision.",
  },
];
