import type { ServiceEntry } from "./types";

const CATEGORY = "permanent-residence";

export const PERMANENT_RESIDENCE_SERVICES: ServiceEntry[] = [
  {
    slug: "express-entry",
    categorySlug: CATEGORY,
    title: "Express Entry",
    icon: "Globe2",
    image: "/images/services/permanent-residence_express-entry.jpg",
    shortDescription: "Canada's points-based system managing applications for three federal economic programs.",
    suitableFor: "Skilled workers with the education, work experience, and language ability to settle economically in Canada.",
    overview: [
      "Express Entry is the federal system that manages applications for permanent residence under three economic programs: the Canadian Experience Class, the Federal Skilled Worker Program, and the Federal Skilled Trades Program.",
      "Rather than applying directly for permanent residence, eligible candidates first create an Express Entry profile. IRCC ranks profiles using the Comprehensive Ranking System (CRS) and periodically invites the highest-ranked candidates to apply.",
      "Because three programs feed into one pool, a candidate's profile is assessed against all three, and the right program for your situation depends on your specific combination of work experience, language scores, and education.",
    ],
    eligibility: [
      "Meeting the minimum criteria for at least one of the three Express Entry programs",
      "Valid language test results (IELTS, CELPIP, TEF, or TCF, depending on language)",
      "Educational Credential Assessment (ECA) for education obtained outside Canada, where applicable",
      "Sufficient proof of funds, unless exempt (such as holding qualifying Canadian work experience)",
      "No criminal or medical inadmissibility concerns",
    ],
    process: [
      { title: "Initial Assessment", text: "We review your education, work history, and language results to see which Express Entry program(s) you may qualify for." },
      { title: "Program & Pathway Review", text: "We identify whether CEC, FSWP, or FSTP fits best — see the three program pages for the specific criteria of each." },
      { title: "Document Preparation", text: "Language tests, ECA, and reference letters are completed or organized before profile creation." },
      { title: "Profile Submission", text: "Your Express Entry profile is created and entered into the pool, generating a CRS score." },
      { title: "CRS Review & Monitoring", text: "We monitor your score against recent invitation rounds and flag ways to improve it, such as additional language testing." },
      { title: "Invitation to Apply (ITA)", text: "If invited, you have a limited window to submit the full permanent residence application." },
      { title: "Application Submission", text: "The complete application, with all supporting documents, is submitted within the ITA deadline." },
      { title: "Processing & Next Steps", text: "IRCC processes the application; we handle any requests for additional documents along the way." },
    ],
    documents: [
      "Language test results (IELTS, CELPIP, TEF, or TCF)",
      "Educational Credential Assessment (ECA), if educated outside Canada",
      "Proof of work experience (reference letters, pay stubs, contracts)",
      "Proof of funds, where required",
      "Valid passport",
      "Police certificates",
      "Medical exam results",
    ],
    commonIssues: [
      "Choosing the wrong program within Express Entry for your actual work history",
      "Language test scores that fall just short of a program's threshold",
      "Reference letters missing details IRCC specifically looks for (duties, hours, pay)",
      "Letting an Invitation to Apply deadline lapse",
      "Incomplete proof of funds documentation",
    ],
    howWeHelp: [
      "Assess your profile against all three Express Entry programs, not just one",
      "Identify realistic ways to strengthen your CRS score before or after profile creation",
      "Review reference letters and documents against what IRCC specifically requires",
      "Manage profile and application deadlines so nothing is missed",
      "Prepare a complete application package once you receive an invitation",
    ],
    faq: [
      { question: "What's the difference between the three Express Entry programs?", answer: "They're built around different types of experience — Canadian work experience, skilled work experience abroad, or a skilled trade — each explained on its own program page." },
      { question: "What is the CRS score?", answer: "The Comprehensive Ranking System score ranks Express Entry profiles using factors like age, education, language ability, and work experience, to decide who receives an invitation." },
      { question: "Can I apply if I'm still outside Canada?", answer: "Yes, Express Entry accepts candidates both inside and outside Canada, provided they meet program requirements." },
      { question: "What happens after I receive an Invitation to Apply?", answer: "You have a limited time window to submit your complete permanent residence application with all required documents." },
      { question: "How long does the whole process take?", answer: "Timelines vary by program and change over time — always check current IRCC processing times rather than relying on past figures." },
      { question: "Can you help me improve my CRS score?", answer: "Yes — we review realistic options such as additional language testing, further education, or gaining qualifying work experience." },
    ],
    relatedSlugs: ["permanent-residence/provincial-nominee-program", "temporary-residence/post-graduation-work-permit", "citizenship/canadian-citizenship"],
    seoTitle: "Express Entry Application Support",
    seoDescription: "Support with Express Entry, including CRS score review, profile preparation, and guidance across the Canadian Experience Class, FSWP, and FSTP.",
    programs: [
      {
        slug: "cec",
        title: "Canadian Experience Class",
        icon: "BadgeCheck",
        image: "/images/services/permanent-residence_express-entry_cec.jpg",
        shortDescription: "For candidates with qualifying skilled work experience in Canada.",
        suitableFor: "People who have worked in Canada in a skilled occupation on valid temporary status.",
        keyConsiderations: ["Requires recent, qualifying Canadian work experience", "No formal education requirement on its own", "Often suits former study or work permit holders already in Canada"],
        overview: [
          "The Canadian Experience Class (CEC) is for candidates who have gained skilled work experience inside Canada, typically while on a work or post-graduation work permit.",
          "It recognizes that time spent working in Canada is itself strong evidence of a candidate's ability to integrate economically.",
        ],
        eligibility: [
          "A minimum period of recent, full-time (or equivalent part-time) skilled work experience in Canada",
          "That experience gained within the qualifying window before application",
          "Language test results meeting the minimum benchmark for the occupation skill level",
          "Legal temporary status while that work experience was gained",
        ],
        process: [
          { title: "Work History Review", text: "We confirm your Canadian work experience meets the hours, skill level, and recency requirements." },
          { title: "Language Testing", text: "You complete a language test meeting the minimum benchmark for your occupation." },
          { title: "Reference Letters", text: "Employer reference letters are prepared with the specific details IRCC requires." },
          { title: "Profile Submission", text: "Your Express Entry profile is created under the CEC program." },
          { title: "Invitation & Application", text: "If invited, the full application is prepared and submitted within the deadline." },
        ],
        documents: ["Detailed employer reference letters", "Pay stubs or T4 slips", "Language test results", "Proof of valid status during the work period"],
        commonIssues: ["Reference letters missing required duty descriptions", "Work experience that falls just short of the minimum period", "Gaps in maintained status during the qualifying work"],
        howWeHelp: ["Verify your work history meets CEC's specific requirements", "Help obtain properly detailed reference letters", "Prepare a complete profile and application"],
        faq: [
          { question: "Does my work experience need to be full-time?", answer: "It needs to meet a minimum total of hours, which can be accumulated through full-time or equivalent part-time work within the qualifying period." },
          { question: "Do I need an Educational Credential Assessment for CEC?", answer: "Not required for CEC eligibility itself, though education can still contribute CRS points if assessed." },
        ],
        seoTitle: "Canadian Experience Class (CEC) Applications",
        seoDescription: "Guidance on Canadian Experience Class eligibility and applications for candidates with qualifying Canadian work experience.",
      },
      {
        slug: "federal-skilled-worker-program",
        title: "Federal Skilled Worker Program",
        icon: "Globe2",
        image: "/images/services/permanent-residence_express-entry_federal-skilled-worker-program.jpg",
        shortDescription: "For candidates with foreign skilled work experience assessed on a points grid.",
        suitableFor: "Skilled workers applying from outside Canada, or with foreign work experience, who meet the selection factor criteria.",
        keyConsiderations: ["Assessed on a separate six-factor selection grid", "Requires an Educational Credential Assessment", "Suited to candidates without Canadian work experience"],
        overview: [
          "The Federal Skilled Worker Program (FSWP) is designed for candidates with skilled work experience gained outside Canada, assessed against a selection grid covering factors like age, education, language ability, and work experience.",
          "It's often the relevant program for candidates applying from abroad who haven't yet worked in Canada.",
        ],
        eligibility: [
          "A minimum period of skilled work experience in an eligible occupation",
          "A passing score on the FSWP six-factor selection grid",
          "Language test results meeting the minimum benchmark",
          "An Educational Credential Assessment for education obtained outside Canada",
          "Proof of funds, unless exempt",
        ],
        process: [
          { title: "Selection Grid Assessment", text: "We score your profile against the FSWP's six factors to confirm you meet the minimum." },
          { title: "ECA & Language Testing", text: "You complete an Educational Credential Assessment and language test." },
          { title: "Work Experience Documentation", text: "Reference letters are prepared confirming skilled work experience abroad." },
          { title: "Profile Submission", text: "Your Express Entry profile is created under the FSWP program." },
          { title: "Invitation & Application", text: "If invited, the full application is prepared with proof of funds and other supporting documents." },
        ],
        documents: ["Educational Credential Assessment report", "Language test results", "Detailed foreign employer reference letters", "Proof of funds"],
        commonIssues: ["Falling short of the FSWP selection grid's minimum passing mark", "Reference letters that don't clearly describe skilled duties", "Missing or outdated ECA report"],
        howWeHelp: ["Score your profile accurately against the selection grid before relying on it", "Guide you through the ECA and language testing process", "Prepare a complete profile and application"],
        faq: [
          { question: "What is the selection grid?", answer: "It's a point system scoring factors like age, education, language, and work experience, separate from the CRS score used to rank Express Entry profiles overall." },
          { question: "Can I apply without ever having visited Canada?", answer: "Yes, FSWP doesn't require Canadian work experience or a prior visit, provided you meet the program's criteria." },
        ],
        seoTitle: "Federal Skilled Worker Program (FSWP) Applications",
        seoDescription: "Guidance on Federal Skilled Worker Program eligibility and applications for candidates with foreign skilled work experience.",
      },
      {
        slug: "federal-skilled-trades-program",
        title: "Federal Skilled Trades Program",
        icon: "Handshake",
        image: "/images/services/permanent-residence_express-entry_federal-skilled-trades-program.jpg",
        shortDescription: "For candidates with qualifying experience in an eligible skilled trade.",
        suitableFor: "Workers with experience in an eligible trade occupation, with or without a certificate of qualification.",
        keyConsiderations: ["Built around a specific list of eligible trade occupations", "A valid job offer or certificate of qualification is generally required", "Language requirements differ from the other two programs"],
        overview: [
          "The Federal Skilled Trades Program (FSTP) is designed for candidates with experience in specific trade occupations, recognizing that trades qualify differently than other skilled work.",
          "It generally requires either a valid job offer in the trade or a certificate of qualification issued by a Canadian province, territory, or federal body.",
        ],
        eligibility: [
          "A minimum period of full-time (or equivalent) experience in an eligible skilled trade",
          "A valid Canadian job offer in that trade, or a certificate of qualification",
          "Language test results meeting the program's minimum benchmark",
          "Meeting the job requirements described in the relevant occupation classification",
        ],
        process: [
          { title: "Trade Eligibility Check", text: "We confirm your occupation is on the eligible trades list and that your experience matches it." },
          { title: "Job Offer or Certificate Review", text: "We help confirm a qualifying job offer or coordinate a certificate of qualification application where applicable." },
          { title: "Language Testing", text: "You complete a language test meeting the FSTP's specific minimum levels." },
          { title: "Profile Submission", text: "Your Express Entry profile is created under the FSTP program." },
          { title: "Invitation & Application", text: "If invited, the full application is prepared with trade-specific supporting documents." },
        ],
        documents: ["Proof of trade work experience", "Certificate of qualification, or a valid job offer letter", "Language test results", "Proof of funds, where required"],
        commonIssues: ["Occupations that don't fall within the FSTP's eligible trade list", "Missing a qualifying job offer or certificate of qualification", "Language scores that meet other programs but not FSTP's specific requirement"],
        howWeHelp: ["Confirm your trade occupation and experience actually qualify", "Help pursue a certificate of qualification where that's the better route", "Prepare a complete profile and application"],
        faq: [
          { question: "Do I need a certificate of qualification to apply?", answer: "You generally need either a valid job offer in the trade or a certificate of qualification — we assess which route fits your situation." },
          { question: "Is the language requirement the same as other Express Entry programs?", answer: "No, FSTP has its own minimum language benchmarks, which can differ from CEC and FSWP." },
        ],
        seoTitle: "Federal Skilled Trades Program (FSTP) Applications",
        seoDescription: "Guidance on Federal Skilled Trades Program eligibility and applications for candidates with experience in an eligible skilled trade.",
      },
    ],
  },
  {
    slug: "provincial-nominee-program",
    categorySlug: CATEGORY,
    title: "Provincial Nominee Program (PNP)",
    icon: "Landmark",
    image: "/images/services/permanent-residence_provincial-nominee-program.jpg",
    shortDescription: "Nomination-based pathways run by individual provinces and territories.",
    suitableFor: "Candidates with a connection to, or interest in, a specific province's labour market or community.",
    overview: [
      "Provincial Nominee Programs allow Canadian provinces and territories to nominate candidates for permanent residence based on their own specific labour market and community needs.",
      "Each province runs its own streams with their own eligibility criteria — some connect directly to Express Entry (an 'enhanced' nomination adding significant CRS points), while others operate as standalone, paper-based streams.",
      "We don't invent or guess at provincial criteria here — the right stream and its exact requirements depend on the specific province and current program guidelines, which we review directly with you.",
    ],
    eligibility: [
      "Meeting the specific criteria of the province's chosen stream, which vary by province",
      "Often a connection to the province — a job offer, prior study, family, or a visit under certain streams",
      "An Express Entry profile, for enhanced (Express Entry-linked) nomination streams",
      "Meeting the province's language, education, or work experience thresholds for that stream",
    ],
    process: [
      { title: "Initial Assessment", text: "We review your profile against the provinces where you may have the strongest connection or eligibility." },
      { title: "Stream Identification", text: "We identify the specific provincial stream(s) that currently match your situation." },
      { title: "Provincial Application", text: "An application (or expression of interest) is prepared for the provincial government." },
      { title: "Provincial Nomination", text: "If nominated, you receive a nomination certificate from the province." },
      { title: "Federal Application", text: "The nomination is then used to apply for permanent residence — through Express Entry or directly to IRCC, depending on the stream." },
      { title: "Federal Processing", text: "IRCC processes the permanent residence application; timelines vary by stream." },
    ],
    documents: [
      "Proof of connection to the province (job offer, study, family, prior visit)",
      "Language test results",
      "Educational Credential Assessment, where required",
      "Proof of funds, depending on the stream",
      "Provincial application forms specific to the chosen stream",
    ],
    commonIssues: [
      "Applying to a stream whose criteria don't actually match the candidate's profile",
      "Assuming all PNP streams work the same way, when requirements differ significantly by province",
      "Missing province-specific document or form requirements",
      "Not accounting for provincial intake caps or stream closures",
    ],
    howWeHelp: [
      "Identify which province and stream genuinely fits your background",
      "Confirm current, province-specific eligibility criteria before you apply",
      "Prepare the provincial application and, where applicable, the linked federal application",
      "Track provincial intake periods and stream availability",
    ],
    faq: [
      { question: "Can I apply to more than one province?", answer: "In some cases yes, but each province's rules on concurrent applications vary, so this needs to be checked before applying to more than one." },
      { question: "Is PNP faster than Express Entry alone?", answer: "An enhanced nomination adds significant CRS points, which can speed up receiving an invitation, but overall timelines still depend on the specific stream and current processing times." },
      { question: "Do I need a job offer for PNP?", answer: "Some streams require one, others don't — this depends entirely on the specific province and stream." },
      { question: "What happens if I'm nominated but don't apply for permanent residence?", answer: "Nominations are generally time-limited, so it's important to move forward with the federal application within the required window." },
    ],
    relatedSlugs: ["permanent-residence/express-entry", "permanent-residence/atlantic-immigration-program", "permanent-residence/rural-community-immigration-pilot"],
    seoTitle: "Provincial Nominee Program (PNP) Guidance",
    seoDescription: "Guidance on Provincial Nominee Program streams and nominations across Canadian provinces and territories.",
  },
  {
    slug: "atlantic-immigration-program",
    categorySlug: CATEGORY,
    title: "Atlantic Immigration Program",
    icon: "MapPin",
    image: "/images/services/permanent-residence_atlantic-immigration-program.jpg",
    shortDescription: "An employer-driven pathway to permanent residence in Canada's Atlantic provinces.",
    suitableFor: "Workers with a qualifying job offer from a designated employer in Nova Scotia, New Brunswick, Prince Edward Island, or Newfoundland and Labrador.",
    overview: [
      "The Atlantic Immigration Program (AIP) is a permanent pathway connecting skilled and intermediate-skilled workers, and certain international graduates, with employers in Canada's four Atlantic provinces.",
      "It's built around a genuine job offer from a designated employer and an individualized settlement plan, rather than a general points-based ranking.",
    ],
    eligibility: [
      "A valid job offer from a designated Atlantic employer meeting the program's requirements",
      "Work experience or education matching the job offer's skill level",
      "Language test results meeting the program's minimum requirement",
      "An educational credential assessment, where education was obtained outside Canada",
      "A completed settlement plan for you and your family",
    ],
    process: [
      { title: "Employer & Offer Review", text: "We confirm the employer is designated under AIP and the job offer meets program requirements." },
      { title: "Candidate Eligibility Check", text: "We review your work experience, education, and language results against the program's criteria." },
      { title: "Settlement Plan", text: "You complete a settlement plan session, often through a designated settlement organization." },
      { title: "Endorsement Application", text: "The employer applies for the province to endorse the job offer." },
      { title: "Permanent Residence Application", text: "With the endorsement, the permanent residence application is submitted to IRCC." },
      { title: "Federal Processing", text: "IRCC processes the application; many candidates can also apply for a temporary work permit to start work sooner." },
    ],
    documents: [
      "Valid job offer from a designated employer",
      "Proof of work experience or education matching the role",
      "Language test results",
      "Educational Credential Assessment, where required",
      "Completed settlement plan confirmation",
    ],
    commonIssues: [
      "Working with an employer who isn't actually designated under the program",
      "A job offer that doesn't meet the minimum skill level or duration requirements",
      "Skipping or delaying the required settlement plan session",
      "Incomplete endorsement application documentation from the employer side",
    ],
    howWeHelp: [
      "Confirm employer designation and job offer eligibility before relying on it",
      "Review your profile against AIP's specific requirements",
      "Coordinate the settlement plan and endorsement process with the employer",
      "Prepare the permanent residence application once endorsed",
    ],
    faq: [
      { question: "Do I need to already be working for the employer?", answer: "No, AIP can apply to a new job offer, but the employer must be designated and the offer must meet program requirements." },
      { question: "Can I work while my application is processing?", answer: "Many candidates apply for a temporary work permit alongside the permanent residence application, letting them start work sooner." },
      { question: "Is a settlement plan really required?", answer: "Yes, it's a specific program requirement intended to support your and your family's transition to the community." },
    ],
    relatedSlugs: ["permanent-residence/provincial-nominee-program", "permanent-residence/rural-community-immigration-pilot"],
    seoTitle: "Atlantic Immigration Program (AIP) Support",
    seoDescription: "Support with Atlantic Immigration Program applications for employer-driven permanent residence in Atlantic Canada.",
  },
  {
    slug: "rural-community-immigration-pilot",
    categorySlug: CATEGORY,
    title: "Rural Community Immigration Pilot",
    icon: "Home",
    image: "/images/services/permanent-residence_rural-community-immigration-pilot.jpg",
    shortDescription: "A community-driven pathway connecting workers with participating rural communities.",
    suitableFor: "Workers with a qualifying job offer from an employer in one of the pilot's participating rural communities.",
    overview: [
      "The Rural Community Immigration Pilot connects foreign workers with employers in smaller, participating communities across Canada that have identified specific economic and labour needs.",
      "Each participating community has its own recommended occupations and process, coordinated with a local economic development organization, so the right next step depends on the specific community and job offer involved.",
    ],
    eligibility: [
      "A qualifying job offer from an employer in a participating community",
      "Work experience matching the job offer and the community's identified in-demand occupations",
      "Language test results meeting the pilot's minimum requirement",
      "Education credentials assessed where obtained outside Canada",
      "A genuine intention to live in the recommending community",
    ],
    process: [
      { title: "Community & Employer Review", text: "We confirm the employer and community are currently participating and the role fits the community's needs." },
      { title: "Candidate Eligibility Check", text: "We review your experience, education, and language results against the pilot's criteria." },
      { title: "Community Recommendation", text: "The local economic development organization reviews the job offer and candidate for a recommendation." },
      { title: "Permanent Residence Application", text: "With a community recommendation, the application is submitted to IRCC." },
      { title: "Federal Processing", text: "IRCC processes the application against standard admissibility requirements." },
    ],
    documents: [
      "Qualifying job offer from a participating community employer",
      "Proof of relevant work experience",
      "Language test results",
      "Educational Credential Assessment, where required",
      "Community recommendation confirmation",
    ],
    commonIssues: [
      "Pursuing a job offer in a community that isn't currently part of the pilot",
      "A role that doesn't match the community's identified occupations",
      "Missing the community-specific recommendation step before applying federally",
    ],
    howWeHelp: [
      "Confirm current participating communities and their identified occupations",
      "Review your eligibility against the specific community's criteria",
      "Help coordinate with the local economic development organization",
      "Prepare the federal application once recommended",
    ],
    faq: [
      { question: "Can I choose which community to apply through?", answer: "You generally need a genuine job offer from an employer in a specific participating community — it isn't a free choice independent of a job offer." },
      { question: "Is this the same as the Provincial Nominee Program?", answer: "No, it's a separate federal pilot coordinated with local communities rather than provincial governments, though both are route to permanent residence tied to a specific location." },
    ],
    relatedSlugs: ["permanent-residence/atlantic-immigration-program", "permanent-residence/provincial-nominee-program"],
    seoTitle: "Rural Community Immigration Pilot Guidance",
    seoDescription: "Guidance on the Rural Community Immigration Pilot for workers with a job offer in a participating rural community.",
  },
  {
    slug: "francophone-community-immigration-pilot",
    categorySlug: CATEGORY,
    title: "Francophone Community Immigration Pilot",
    icon: "Languages",
    image: "/images/services/permanent-residence_francophone-community-immigration-pilot.jpg",
    shortDescription: "A community-driven pathway supporting French-speaking immigration outside Quebec.",
    suitableFor: "French-speaking workers with a qualifying job offer from an employer in a participating Francophone minority community.",
    overview: [
      "The Francophone Community Immigration Pilot supports French-speaking newcomers settling in Francophone minority communities outside Quebec, connecting them with local employers and community organizations.",
      "Like the Rural Community pilot, it's built around a specific job offer and a community recommendation, with an added focus on French language ability and community integration.",
    ],
    eligibility: [
      "A qualifying job offer from an employer in a participating Francophone community",
      "French language ability meeting the pilot's minimum requirement",
      "Work experience matching the job offer and community's identified needs",
      "Education credentials assessed where obtained outside Canada",
      "A genuine intention to live in and contribute to the Francophone community",
    ],
    process: [
      { title: "Community & Employer Review", text: "We confirm the employer and community are currently participating in the pilot." },
      { title: "Candidate Eligibility Check", text: "We review your French language results, experience, and education against the pilot's criteria." },
      { title: "Community Recommendation", text: "The local Francophone economic development organization reviews the job offer and candidate." },
      { title: "Permanent Residence Application", text: "With a recommendation, the application is submitted to IRCC." },
      { title: "Federal Processing", text: "IRCC processes the application against standard admissibility requirements." },
    ],
    documents: [
      "Qualifying job offer from a participating Francophone community employer",
      "French language test results",
      "Proof of relevant work experience",
      "Educational Credential Assessment, where required",
      "Community recommendation confirmation",
    ],
    commonIssues: [
      "Language results that don't meet the pilot's specific French proficiency requirement",
      "A job offer from an employer or community not currently part of the pilot",
      "Missing the community recommendation step before applying federally",
    ],
    howWeHelp: [
      "Confirm current participating Francophone communities and employers",
      "Review your French language results against the pilot's requirement",
      "Coordinate with the local Francophone economic development organization",
      "Prepare the federal application once recommended",
    ],
    faq: [
      { question: "Do I need to be fluent in both English and French?", answer: "The pilot focuses on French language ability specifically; requirements for English vary and should be confirmed for your situation." },
      { question: "Is this pathway only for Quebec?", answer: "No — it specifically supports Francophone minority communities outside Quebec, which has its own separate immigration programs." },
    ],
    relatedSlugs: ["permanent-residence/rural-community-immigration-pilot", "permanent-residence/atlantic-immigration-program"],
    seoTitle: "Francophone Community Immigration Pilot Support",
    seoDescription: "Support with the Francophone Community Immigration Pilot for French-speaking workers with a job offer in a participating community.",
  },
];
