import type { ServiceEntry } from "./types";

const CATEGORY = "temporary-residence";

export const TEMPORARY_RESIDENCE_SERVICES: ServiceEntry[] = [
  {
    slug: "visitor-visa",
    categorySlug: CATEGORY,
    title: "Visitor Visa",
    icon: "Plane",
    image: "/images/services/temporary-residence_visitor-visa.jpg",
    shortDescription: "A temporary resident visa for visiting Canada for tourism, family, or short business trips.",
    suitableFor: "People who want to visit family, see Canada, or attend a short business trip and need a visa to enter.",
    overview: [
      "A visitor visa (officially a Temporary Resident Visa) is the document some travellers need to enter Canada for a temporary stay — commonly to see family, travel, or attend a short business meeting or conference.",
      "Whether you need one at all depends on your citizenship: travellers from many countries need a visa, while others only need an Electronic Travel Authorization (eTA) when flying in. A consultant can help confirm which applies to you before you prepare anything else.",
      "A visitor visa does not permit working or studying in Canada — it's specifically for temporary, non-immigrant visits.",
    ],
    eligibility: [
      "A valid passport or other acceptable travel document",
      "A genuine, clearly explained purpose for the visit",
      "Sufficient funds to cover the trip and your stay",
      "Strong enough ties to your home country (work, family, property) to support an intent to return",
      "No criminal or medical inadmissibility concerns",
      "A clean immigration history, or a reasonable explanation where one exists",
    ],
    process: [
      { title: "Initial Assessment", text: "We review your travel purpose, history, and ties to your home country to see how the application is likely to be viewed." },
      { title: "Document Collection", text: "You gather financial, employment, and travel-purpose documents while we confirm what's actually needed for your situation." },
      { title: "Application Preparation", text: "We prepare the forms and a cover letter that presents your purpose and ties clearly and consistently." },
      { title: "Biometrics", text: "Most applicants need to give fingerprints and a photo at a service point, unless a recent exemption applies." },
      { title: "Submission", text: "The complete application is submitted online or on paper, depending on what fits your circumstances." },
      { title: "Government Processing", text: "IRCC reviews the file; processing time varies by visa office and is outside anyone's control." },
      { title: "Responding to Requests", text: "If IRCC asks for more information or an interview, we help you prepare a timely, complete response." },
      { title: "Decision", text: "Once approved, the visa is placed in your passport and you can plan your travel to Canada." },
    ],
    documents: [
      "Valid passport",
      "Digital photo meeting IRCC specifications",
      "Proof of funds (bank statements, pay stubs)",
      "Letter explaining the purpose and length of the visit",
      "Evidence of ties to your home country (employment letter, property, family)",
      "Invitation letter from a host in Canada, if applicable",
      "Travel itinerary or proof of onward travel, if available",
    ],
    commonIssues: [
      "A purpose-of-visit letter that is vague or inconsistent with the supporting documents",
      "Financial evidence that doesn't clearly show funds are available and stable",
      "Weak or unclear evidence of ties to the home country",
      "Incomplete forms or missing signatures",
      "Applying with an expired or soon-to-expire passport",
    ],
    howWeHelp: [
      "Assess whether you need a visa or an eTA before you apply for the wrong thing",
      "Review your travel history and ties to identify what needs stronger evidence",
      "Prepare a clear, consistent application package and cover letter",
      "Check financial and supporting documents before submission",
      "Track the application and respond to any IRCC requests on your behalf",
    ],
    faq: [
      { question: "How long can I stay in Canada on a visitor visa?", answer: "The length of stay is set by the border officer at entry, not by the visa itself, and is usually stamped or noted in your passport. It's commonly up to six months, but this can vary." },
      { question: "Can I extend my visit once I'm in Canada?", answer: "In many cases yes, by applying for a visitor record before your authorized stay expires. Requirements and outcomes vary by circumstances." },
      { question: "How long does processing take?", answer: "Processing times vary significantly by visa office and change over time. Always check current IRCC processing times for your country before planning travel." },
      { question: "What's the difference between a single-entry and multiple-entry visa?", answer: "A single-entry visa allows one entry to Canada, while a multiple-entry visa allows repeated entries during its validity. IRCC generally issues multiple-entry visas unless there's a specific reason not to." },
      { question: "What happens if my visa application is refused?", answer: "You'll receive a refusal letter citing the officer's concerns. Depending on the reasons, it may be possible to address them and reapply." },
    ],
    relatedSlugs: ["temporary-residence/super-visa", "temporary-residence/study-permit", "family-sponsorship/spousal-sponsorship"],
    seoTitle: "Visitor Visa Services",
    seoDescription: "Guidance on applying for a Canadian visitor visa (Temporary Resident Visa), including eligibility, documents, and the application process.",
  },
  {
    slug: "study-permit",
    categorySlug: CATEGORY,
    title: "Study Permit",
    icon: "GraduationCap",
    image: "/images/services/temporary-residence_study-permit.jpg",
    shortDescription: "The authorization required to study at a Designated Learning Institution in Canada.",
    suitableFor: "Prospective international students accepted into a program at a Canadian Designated Learning Institution (DLI).",
    overview: [
      "A study permit is the document that authorizes a foreign national to study at a Designated Learning Institution (DLI) in Canada for programs longer than six months.",
      "An offer of admission from a DLI is the starting point — the study permit application is built around that offer, your ability to support yourself financially, and your overall profile as a temporary resident.",
      "Some provinces require a Provincial or Territorial Attestation Letter (PAL/TAL) as part of the application, reflecting a limit on the number of study permits processed each year.",
    ],
    eligibility: [
      "A letter of acceptance from a recognized Designated Learning Institution",
      "Proof of sufficient funds for tuition and living expenses",
      "A Provincial or Territorial Attestation Letter, where currently required",
      "No criminal or medical inadmissibility concerns",
      "A credible explanation of your study plan and how it fits your background",
      "Willingness to leave Canada at the end of your authorized stay, consistent with program rules",
    ],
    process: [
      { title: "Initial Assessment", text: "We review your acceptance letter, academic background, and finances to map out what the application needs." },
      { title: "Attestation Letter Check", text: "We confirm whether your province currently requires a PAL/TAL and coordinate with you on obtaining it." },
      { title: "Financial Documentation", text: "You assemble proof of funds; we check it meets the amount and format IRCC expects." },
      { title: "Application Preparation", text: "We prepare the forms and a study plan letter that ties your program choice to your goals." },
      { title: "Biometrics & Submission", text: "Biometrics are completed where required, and the full application is submitted." },
      { title: "Government Processing", text: "IRCC reviews the application; timelines vary by country of application and time of year." },
      { title: "Study Permit Issuance", text: "Once approved, you receive your port of entry letter and, where applicable, your visa." },
      { title: "Arrival in Canada", text: "We go over what to expect at the border and how your study permit is activated on arrival." },
    ],
    documents: [
      "Letter of acceptance from a DLI",
      "Provincial/Territorial Attestation Letter, where required",
      "Proof of funds (tuition, living costs, travel)",
      "Valid passport and photos",
      "Academic transcripts and credentials",
      "Language test results, if required by your program",
      "Statement of purpose or study plan",
    ],
    commonIssues: [
      "Proof of funds that doesn't meet the required amount or isn't well documented",
      "A study plan that doesn't clearly connect past education to the chosen program",
      "Applying without confirming whether a PAL/TAL is required",
      "Gaps in education or employment history left unexplained",
      "Submitting an incomplete set of supporting documents",
    ],
    howWeHelp: [
      "Review your acceptance letter and confirm program and DLI eligibility",
      "Confirm whether a PAL/TAL applies to your situation",
      "Help structure financial evidence to meet IRCC's expectations",
      "Draft a study plan that presents your academic path clearly",
      "Monitor the application and handle follow-up requests",
    ],
    faq: [
      { question: "Can I work while studying on a study permit?", answer: "Many study permit holders can work on or off campus within program rules, but hours and eligibility depend on current regulations and your specific permit conditions." },
      { question: "Can my spouse or children come with me?", answer: "In many cases a spouse or common-law partner and dependent children can apply for their own permits, but eligibility depends on your program and current rules — we assess this case by case." },
      { question: "Will I automatically qualify for a work permit after graduation?", answer: "Not automatically. Post-Graduation Work Permit eligibility depends on your program, institution, and current PGWP rules in effect when you apply." },
      { question: "What if I don't meet the funds requirement?", answer: "There may be other ways to demonstrate financial support, such as a sponsor or scholarship, but this needs to be assessed against current requirements." },
      { question: "How far in advance should I apply?", answer: "As early as possible once you have your acceptance letter, since processing times vary and some documents (like a PAL) take time to obtain." },
    ],
    relatedSlugs: ["temporary-residence/post-graduation-work-permit", "temporary-residence/spousal-open-work-permit", "permanent-residence/express-entry"],
    seoTitle: "Study Permit Application Support",
    seoDescription: "Support with Canadian study permit applications, including eligibility, attestation letters, documents, and the application process.",
  },
  {
    slug: "spousal-open-work-permit",
    categorySlug: CATEGORY,
    title: "Spousal Open Work Permit",
    icon: "HeartHandshake",
    image: "/images/services/temporary-residence_spousal-open-work-permit.jpg",
    shortDescription: "An open work permit for the spouse or partner of certain permit holders or applicants.",
    suitableFor: "Spouses or common-law partners of eligible work or study permit holders, or of certain permanent residence applicants.",
    overview: [
      "A spousal open work permit allows the spouse or common-law partner of an eligible principal applicant to work for almost any employer in Canada, rather than being tied to one job.",
      "Eligibility depends heavily on the principal applicant's own status — their permit type, skill level, or stage in a permanent residence process. These eligibility categories have changed in recent years, so this needs to be checked against current IRCC rules rather than assumed.",
      "Because eligibility rules can change, we always confirm current criteria before advising on whether this pathway is open to you.",
    ],
    eligibility: [
      "A genuine spousal or common-law relationship with the principal applicant",
      "The principal applicant holds a qualifying permit or application status, per current IRCC criteria",
      "Valid status for both partners while the open work permit is processed, where applicable",
      "No criminal or medical inadmissibility concerns",
      "Supporting evidence of the relationship (joint finances, shared residence, communication)",
    ],
    process: [
      { title: "Initial Assessment", text: "We confirm whether the principal applicant's status currently qualifies a spouse for an open work permit." },
      { title: "Relationship Evidence Review", text: "We identify what evidence best supports a genuine relationship for your situation." },
      { title: "Application Preparation", text: "Forms are prepared for both the principal applicant (if needed) and the spouse." },
      { title: "Submission", text: "The application is submitted together with, or linked to, the principal applicant's file as required." },
      { title: "Government Processing", text: "IRCC processes the open work permit application; timelines vary by category and office." },
      { title: "Work Permit Issuance", text: "Once approved, the permit allows the spouse to work for most employers in Canada." },
    ],
    documents: [
      "Proof of the relationship (marriage certificate or common-law evidence)",
      "Principal applicant's permit or application confirmation",
      "Valid passport and photos for both partners",
      "Evidence of a shared household or ongoing relationship",
      "Application forms specific to open work permits",
    ],
    commonIssues: [
      "Assuming eligibility without checking the principal applicant's current status category",
      "Weak relationship evidence, especially for common-law partners",
      "Submitting the spousal application before confirming the principal applicant's own status is in order",
      "Missing or outdated forms specific to open work permit categories",
    ],
    howWeHelp: [
      "Check current IRCC eligibility rules against your specific situation before you apply",
      "Advise on what relationship evidence will meaningfully support the file",
      "Coordinate the timing between the principal applicant's status and the spousal application",
      "Prepare and review the full application package",
    ],
    faq: [
      { question: "Is every spouse of a work or study permit holder eligible?", answer: "No — eligibility depends on the principal applicant's specific permit category, which has changed over time. We confirm this against current rules before proceeding." },
      { question: "Can I apply at the same time as my spouse's own application?", answer: "In many cases yes, but the approach depends on both applications' status and timing, which we assess together." },
      { question: "Is this an open work permit, meaning I can work anywhere?", answer: "Yes, where approved, it generally allows work for most employers, unlike an employer-specific work permit." },
      { question: "What if my spouse's status changes while my application is pending?", answer: "This can affect your application, so it's important to tell us right away if anything changes with the principal applicant's status." },
    ],
    relatedSlugs: ["temporary-residence/study-permit", "temporary-residence/employer-specific-work-permit", "family-sponsorship/spousal-sponsorship"],
    seoTitle: "Spousal Open Work Permit Guidance",
    seoDescription: "Guidance on spousal open work permit eligibility and applications for partners of eligible permit holders, based on current IRCC criteria.",
  },
  {
    slug: "super-visa",
    categorySlug: CATEGORY,
    title: "Super Visa",
    icon: "Users",
    image: "/images/services/temporary-residence_super-visa.jpg",
    shortDescription: "A long-validity multiple-entry visa for parents and grandparents of Canadians.",
    suitableFor: "Parents and grandparents of Canadian citizens or permanent residents who want to visit for extended periods.",
    overview: [
      "The Super Visa is a multiple-entry temporary resident visa designed specifically for parents and grandparents of Canadian citizens or permanent residents, allowing longer stays than a standard visitor visa.",
      "It depends on an invitation and financial undertaking from the host child or grandchild in Canada, along with private medical insurance that meets a minimum coverage standard.",
      "It is a visa, not permanent residence — it's a route to spend extended time with family while a permanent option, if wanted, is considered separately.",
    ],
    eligibility: [
      "A parent or grandparent relationship to a Canadian citizen or permanent resident host",
      "A written invitation letter from the host, including their commitment to provide financial support",
      "The host's income meeting the applicable minimum income threshold",
      "Private medical insurance from an approved provider meeting the minimum coverage amount",
      "A medical exam, where required",
      "No criminal or medical inadmissibility concerns",
    ],
    process: [
      { title: "Invitation & Income Review", text: "We review the host's income documentation against the current threshold requirement." },
      { title: "Medical Insurance", text: "We confirm what the insurance policy needs to cover before you purchase it, to avoid a mismatch at submission." },
      { title: "Medical Exam", text: "We coordinate the timing of any required medical exam with an approved panel physician." },
      { title: "Application Preparation", text: "Forms, the invitation letter, and supporting evidence are compiled into a complete package." },
      { title: "Submission", text: "The application is submitted along with biometrics where required." },
      { title: "Government Processing", text: "IRCC processes the application; timelines vary by visa office." },
      { title: "Visa Issuance & Travel", text: "Once approved, the Super Visa is placed in the applicant's passport for travel planning." },
    ],
    documents: [
      "Invitation letter from the host in Canada",
      "Proof of relationship (birth certificates showing the parent/grandparent link)",
      "Host's proof of income (Notice of Assessment, employment letter)",
      "Private medical insurance confirmation meeting minimum coverage",
      "Valid passport and photos",
      "Medical exam results, where required",
    ],
    commonIssues: [
      "Host income documentation that doesn't clearly meet the threshold",
      "Insurance policies that don't meet the minimum coverage amount or duration",
      "Incomplete or inconsistent relationship evidence",
      "Delays caused by purchasing insurance before confirming the correct coverage requirements",
    ],
    howWeHelp: [
      "Assess the host's income against current requirements before you apply",
      "Advise on what the medical insurance policy must include",
      "Prepare a complete, well-organized invitation and supporting package",
      "Track the application and respond to any requests from IRCC",
    ],
    faq: [
      { question: "How long can a visit last on a Super Visa?", answer: "The Super Visa allows for extended stays per visit, longer than a standard visitor visa, for a validity period set at approval. Current limits should be confirmed with us before travel." },
      { question: "Does the host need a minimum income?", answer: "Yes, the host must meet a minimum income threshold that varies with family size, based on current published figures." },
      { question: "Can the Super Visa lead to permanent residence?", answer: "Not on its own. Parents and grandparents wanting to immigrate permanently would generally look at the Parents and Grandparents Sponsorship program separately." },
      { question: "What insurance is required?", answer: "Private medical insurance from a Canadian insurance company, covering at least the minimum amount currently set by IRCC, valid for at least one year from entry." },
    ],
    relatedSlugs: ["family-sponsorship/parents-grandparents-sponsorship", "temporary-residence/visitor-visa"],
    seoTitle: "Super Visa Applications for Parents & Grandparents",
    seoDescription: "Help with Super Visa applications for parents and grandparents of Canadian citizens and permanent residents, including income and insurance requirements.",
  },
  {
    slug: "post-graduation-work-permit",
    categorySlug: CATEGORY,
    title: "Post-Graduation Work Permit",
    icon: "BookOpen",
    image: "/images/services/temporary-residence_post-graduation-work-permit.jpg",
    shortDescription: "An open work permit for eligible graduates of Canadian study programs.",
    suitableFor: "Recent graduates of an eligible program at a Designated Learning Institution.",
    overview: [
      "The Post-Graduation Work Permit (PGWP) allows eligible graduates of Canadian post-secondary programs to gain open work experience in Canada, which can later support a permanent residence application.",
      "Eligibility depends on factors such as the length and type of your study program, the institution attended, and maintaining your status throughout your studies — all of which are assessed under current IRCC rules.",
      "There's generally a limited window after finishing your studies in which to apply, so timing matters.",
    ],
    eligibility: [
      "Completion of an eligible program at a Designated Learning Institution",
      "Maintained full-time student status throughout the program, with limited exceptions",
      "A valid study permit at the time of application, or application within the allowed post-expiry window",
      "Receipt of a confirmation of completion from the institution",
      "Applying within the current eligibility window after your program ends",
    ],
    process: [
      { title: "Program Eligibility Check", text: "We confirm your specific program and institution currently qualify for a PGWP." },
      { title: "Study History Review", text: "We check your study permit history for any gaps or status issues that could affect eligibility." },
      { title: "Document Collection", text: "You obtain your official transcript and confirmation of completion from your institution." },
      { title: "Application Preparation", text: "We prepare the application, including addressing any history issues proactively." },
      { title: "Submission", text: "The application is submitted within the required window." },
      { title: "Government Processing", text: "IRCC processes the request; many graduates can continue working under maintained status while it's pending, subject to conditions." },
      { title: "Permit Issuance", text: "Once approved, the open work permit is issued for a length tied to your program." },
    ],
    documents: [
      "Official transcript",
      "Confirmation of completion letter from the institution",
      "Valid passport",
      "Study permit history",
      "Proof of program length and type (for permit duration calculation)",
    ],
    commonIssues: [
      "Missing the application window after program completion",
      "A program or institution that isn't PGWP-eligible",
      "Gaps in maintaining full-time student status during the program",
      "Applying with an expired study permit without confirming the allowed grace period",
    ],
    howWeHelp: [
      "Confirm your program and institution's PGWP eligibility before you rely on it",
      "Review your study history for anything that could complicate the application",
      "Prepare a complete, correctly timed application",
      "Advise on your ability to work while the application is processed",
    ],
    faq: [
      { question: "How long will my PGWP be valid for?", answer: "Permit length is generally tied to the length of your study program, up to a current maximum set by IRCC." },
      { question: "Can I apply for a PGWP more than once?", answer: "Generally, a person can only receive one PGWP in their lifetime, so timing and program choice matter." },
      { question: "Can I keep working while my application is being processed?", answer: "In many cases yes, under maintained status, but this depends on applying before your study permit expires and other conditions." },
      { question: "Does the PGWP help with permanent residence?", answer: "Canadian work experience gained on a PGWP can strengthen a future Express Entry or other permanent residence application, depending on the category." },
    ],
    relatedSlugs: ["temporary-residence/study-permit", "permanent-residence/express-entry", "temporary-residence/employer-specific-work-permit"],
    seoTitle: "Post-Graduation Work Permit (PGWP) Assistance",
    seoDescription: "Assistance with Post-Graduation Work Permit eligibility and applications for graduates of Canadian Designated Learning Institutions.",
  },
  {
    slug: "employer-specific-work-permit",
    categorySlug: CATEGORY,
    title: "Employer-Specific Work Permit",
    icon: "Briefcase",
    image: "/images/services/temporary-residence_employer-specific-work-permit.jpg",
    shortDescription: "A work permit tied to a specific Canadian employer and job offer.",
    suitableFor: "Workers with a confirmed Canadian job offer who need a permit tied to that specific employer.",
    overview: [
      "An employer-specific work permit authorizes a foreign worker to work for one named employer, in a specific job, usually for a set period, based on the conditions listed on the permit.",
      "Most employer-specific permits are supported by either a Labour Market Impact Assessment (LMIA) or an LMIA exemption under a specific program category.",
      "Because the permit is tied to the employer and role, a job or employer change generally requires a new application.",
    ],
    eligibility: [
      "A genuine, specific job offer from a Canadian employer",
      "A positive LMIA, or a valid LMIA exemption category",
      "Qualifications and experience matching the job offer",
      "The employer meeting its compliance obligations",
      "No criminal or medical inadmissibility concerns",
    ],
    process: [
      { title: "Job Offer Review", text: "We review the job offer and determine whether it needs an LMIA or qualifies for an exemption." },
      { title: "LMIA or Exemption Pathway", text: "We help the employer (or confirm the employer has) completed the LMIA process, or identify the correct exemption." },
      { title: "Worker Qualification Check", text: "We confirm your experience and credentials match what the job offer requires." },
      { title: "Application Preparation", text: "The work permit application is prepared with the job offer, LMIA or exemption reference, and your documents." },
      { title: "Submission", text: "The application is submitted, with biometrics where required." },
      { title: "Government Processing", text: "IRCC reviews the application against the job offer and your qualifications." },
      { title: "Permit Issuance", text: "Once approved, the permit is issued for the named employer and role." },
    ],
    documents: [
      "Written job offer or employment contract",
      "LMIA confirmation or LMIA-exemption reference number",
      "Proof of qualifications and relevant experience",
      "Valid passport and photos",
      "Employer compliance fee payment confirmation",
    ],
    commonIssues: [
      "A mismatch between your experience and the job offer's requirements",
      "Submitting before the LMIA or exemption process is actually complete",
      "Incomplete employer compliance documentation",
      "Job duties on the offer that don't match the National Occupational Classification used",
    ],
    howWeHelp: [
      "Review whether the job offer needs an LMIA or qualifies for an exemption",
      "Coordinate with the employer on compliance requirements",
      "Confirm your qualifications align with the role before submission",
      "Prepare a complete application package for both worker and employer documentation",
    ],
    faq: [
      { question: "Can I change employers on this permit?", answer: "Generally no — an employer-specific permit is tied to the named employer and role, so a change usually requires a new application." },
      { question: "Does every job offer need an LMIA?", answer: "No. Some categories are LMIA-exempt under specific international agreements or program rules, which we assess based on the job and your background." },
      { question: "Who applies for the LMIA — me or my employer?", answer: "The employer applies for the LMIA. We can support the employer through that process or work from an LMIA they've already obtained." },
      { question: "Can this lead to permanent residence?", answer: "Canadian work experience under this permit can support certain permanent residence pathways, such as Express Entry's Canadian Experience Class, depending on your specific profile." },
    ],
    relatedSlugs: ["temporary-residence/lmia", "permanent-residence/express-entry", "temporary-residence/post-graduation-work-permit"],
    seoTitle: "Employer-Specific Work Permit Support",
    seoDescription: "Support for employer-specific work permit applications, including LMIA coordination and LMIA-exempt pathways.",
  },
  {
    slug: "lmia",
    categorySlug: CATEGORY,
    title: "Labour Market Impact Assessment (LMIA)",
    icon: "ClipboardList",
    image: "/images/services/temporary-residence_lmia.jpg",
    shortDescription: "Support for employers seeking to hire a temporary foreign worker through an LMIA.",
    suitableFor: "Canadian employers who want to hire a foreign worker where no LMIA exemption applies.",
    overview: [
      "A Labour Market Impact Assessment (LMIA) is a document an employer may need before hiring a foreign worker, confirming that there's a genuine need for the worker and that hiring them won't negatively affect the Canadian labour market.",
      "The process involves the employer demonstrating recruitment efforts, offering a wage consistent with the position, and meeting other program requirements set by Employment and Social Development Canada (ESDC).",
      "A positive LMIA then supports the foreign worker's own work permit application.",
    ],
    eligibility: [
      "A genuine job vacancy with a legitimate Canadian business",
      "Documented recruitment efforts meeting current advertising requirements",
      "A wage at or above the prevailing wage for the occupation and region",
      "Compliance with past LMIA conditions, if the employer has hired temporary foreign workers before",
      "Complete business and financial documentation supporting the job offer",
    ],
    process: [
      { title: "Employer Assessment", text: "We review the business, the role, and whether the LMIA stream fits the hiring need." },
      { title: "Recruitment Documentation", text: "We confirm the recruitment steps taken meet current requirements before the application is filed." },
      { title: "Wage & Job Offer Review", text: "We check the offered wage against the prevailing wage for the occupation and location." },
      { title: "Application Preparation", text: "The LMIA application is prepared with all required business and recruitment evidence." },
      { title: "Submission to ESDC", text: "The application is submitted to Employment and Social Development Canada for review." },
      { title: "Government Processing", text: "ESDC reviews the application; processing times vary by stream and volume." },
      { title: "Decision & Next Steps", text: "A positive LMIA then supports the foreign worker's employer-specific work permit application." },
    ],
    documents: [
      "Business registration and ownership documents",
      "Proof of recruitment efforts (job postings, records of applicants considered)",
      "Detailed job offer, including wage and duties",
      "Financial statements or proof of business operations",
      "Transition plan, where applicable to the stream",
    ],
    commonIssues: [
      "Recruitment efforts that don't meet the minimum advertising requirements or timeframes",
      "An offered wage below the current prevailing wage for the occupation",
      "Incomplete or inconsistent business documentation",
      "Job duties that don't align with the chosen occupation classification",
    ],
    howWeHelp: [
      "Assess which LMIA stream fits the employer's hiring need",
      "Advise on recruitment steps before they're carried out, not after",
      "Check the wage offer against current prevailing wage data",
      "Prepare a complete, well-documented LMIA application",
    ],
    faq: [
      { question: "How long does an LMIA take to process?", answer: "Processing times vary by stream and change periodically — we check current ESDC processing times before setting expectations." },
      { question: "Does a positive LMIA guarantee the work permit will be approved?", answer: "No. A positive LMIA supports the work permit application, but IRCC still assesses the worker separately against admissibility and other requirements." },
      { question: "Can a small business apply for an LMIA?", answer: "Yes, businesses of various sizes can apply, provided they meet the program's recruitment, wage, and documentation requirements." },
      { question: "What if the LMIA application is refused?", answer: "Depending on the reasons, it may be possible to address the concerns and reapply, or to explore an LMIA-exempt pathway instead." },
    ],
    relatedSlugs: ["temporary-residence/employer-specific-work-permit", "other-immigration-services/business-immigration"],
    seoTitle: "LMIA Support for Canadian Employers",
    seoDescription: "Support for Canadian employers preparing a Labour Market Impact Assessment (LMIA) to hire a temporary foreign worker.",
  },
  {
    slug: "international-experience-canada",
    categorySlug: CATEGORY,
    title: "International Experience Canada (IEC)",
    icon: "Compass",
    image: "/images/services/temporary-residence_international-experience-canada.jpg",
    shortDescription: "Working holiday and youth mobility programs for citizens of partner countries.",
    suitableFor: "Young adults from IEC partner countries who want to work and travel in Canada.",
    overview: [
      "International Experience Canada (IEC) is a youth mobility arrangement between Canada and a number of partner countries, allowing eligible young adults to live and work in Canada temporarily.",
      "IEC is organized into three categories — Working Holiday, Young Professionals, and International Co-op (Internship) — each suited to a different kind of work experience, outlined on their own pages.",
      "Eligibility, age limits, and annual quotas are set per partner country and can change, so we confirm current details for your specific country before you create a profile.",
    ],
    eligibility: [
      "Citizenship of a country with an active IEC agreement with Canada",
      "Meeting the current age range for your country's agreement",
      "Sufficient funds to support yourself at the start of your stay",
      "No criminal or medical inadmissibility concerns",
      "Being selected from the pool for the category you apply to",
    ],
    process: [
      { title: "Country & Category Check", text: "We confirm your country's current IEC agreement, age limits, and which category fits your plans." },
      { title: "Pool Profile Creation", text: "You create a profile in the IEC pool for your chosen category or categories." },
      { title: "Invitation to Apply", text: "If selected in a round of invitations, you have a limited window to submit a full application." },
      { title: "Application Preparation", text: "We help prepare the full work permit application once you're invited." },
      { title: "Submission", text: "The complete application is submitted within the invitation deadline." },
      { title: "Government Processing", text: "IRCC processes the application; timelines vary by volume and time of year." },
      { title: "Permit Issuance & Travel", text: "Once approved, you receive your port of entry letter to activate the permit on arrival." },
    ],
    documents: [
      "Valid passport from an IEC partner country",
      "Proof of funds",
      "Pool profile confirmation",
      "Invitation to apply (once received)",
      "Supporting documents specific to your chosen category (see program pages)",
    ],
    commonIssues: [
      "Missing a country's specific round dates or quota for the year",
      "An incomplete pool profile that doesn't reflect current information",
      "Letting the invitation-to-apply deadline lapse",
      "Applying to the wrong category for your actual plans in Canada",
    ],
    howWeHelp: [
      "Confirm your country's current IEC terms, age range, and quota status",
      "Help you choose the right category among the three IEC streams",
      "Keep your pool profile accurate and ready for an invitation",
      "Prepare a complete application quickly once you're invited, given the tight deadlines",
    ],
    faq: [
      { question: "Can I apply to more than one IEC category?", answer: "In many cases you can create profiles in more than one category if you're eligible for each, improving your chances of an invitation." },
      { question: "How is someone selected from the pool?", answer: "Selection happens through periodic rounds of invitations specific to each country and category, based on current quotas." },
      { question: "Can I extend my stay once I'm working in Canada under IEC?", answer: "IEC permits are generally not extendable beyond their fixed validity, though your individual situation should be assessed directly." },
      { question: "What's the difference between the three IEC categories?", answer: "They're built around different goals — open working holiday experience, a specific professional job offer, or a structured internship/co-op — explained on each program's own page." },
    ],
    relatedSlugs: ["temporary-residence/employer-specific-work-permit", "temporary-residence/post-graduation-work-permit"],
    seoTitle: "International Experience Canada (IEC) Guidance",
    seoDescription: "Guidance on International Experience Canada (IEC) working holiday and youth mobility programs for citizens of partner countries.",
    programs: [
      {
        slug: "working-holiday",
        title: "Working Holiday",
        icon: "Compass",
        image: "/images/services/temporary-residence_international-experience-canada_working-holiday.jpg",
        shortDescription: "Open work permit experience to fund independent travel in Canada.",
        suitableFor: "Young travellers who want an open work permit to support travel around Canada.",
        keyConsiderations: ["Open work permit — not tied to one employer", "Based on a random pool draw within your country's quota", "Funds requirement to support your early stay"],
        overview: [
          "The Working Holiday category issues an open work permit, letting participants work for almost any employer while they travel — a common choice for backpacking and seasonal work.",
          "Selection is generally through a random draw from the pool rather than employer sponsorship, so there's no job offer requirement to enter the pool.",
        ],
        eligibility: [
          "Citizenship of a partner country with a Working Holiday category open",
          "Meeting the current age range for your country's agreement",
          "Proof of funds to support the early part of your stay",
          "No criminal or medical inadmissibility concerns",
        ],
        process: [
          { title: "Profile Creation", text: "Create an IEC pool profile under the Working Holiday category for your country." },
          { title: "Pool Draw", text: "Profiles are entered into periodic random draws within the country's quota." },
          { title: "Invitation to Apply", text: "If drawn, you have a set window to submit your full application." },
          { title: "Application & Submission", text: "We help prepare and submit the work permit application before the deadline." },
          { title: "Permit Issuance", text: "Once approved, your port of entry letter lets you activate the permit on arrival." },
        ],
        documents: ["Valid passport", "Proof of funds", "Pool profile and invitation confirmation", "Passport photos"],
        commonIssues: ["Missing the application deadline after an invitation", "Insufficient documented funds", "Incomplete pool profile details"],
        howWeHelp: ["Confirm your country's quota and timing", "Keep your profile accurate and ready", "Prepare your application quickly once invited"],
        faq: [
          { question: "Do I need a job offer for Working Holiday?", answer: "No — this category doesn't require a job offer to enter the pool or receive an invitation." },
          { question: "Can I work for multiple employers?", answer: "Yes, the open work permit isn't tied to a single employer, within the conditions on the permit." },
        ],
        seoTitle: "IEC Working Holiday Program",
        seoDescription: "Guidance on the International Experience Canada Working Holiday category, including eligibility and the application process.",
      },
      {
        slug: "young-professionals",
        title: "Young Professionals",
        icon: "Briefcase",
        image: "/images/services/temporary-residence_international-experience-canada_young-professionals.jpg",
        shortDescription: "An employer-specific permit for professional work experience tied to a job offer.",
        suitableFor: "Young professionals with a qualifying job offer contributing to their career development.",
        keyConsiderations: ["Requires a genuine job offer in your field", "Employer-specific work permit, not open", "Job should support your professional development"],
        overview: [
          "The Young Professionals category issues an employer-specific work permit, intended for participants who have a job offer that contributes meaningfully to their career.",
          "Unlike Working Holiday, this category requires a job offer before you can enter the pool for this stream.",
        ],
        eligibility: [
          "Citizenship of a partner country with this category open",
          "A genuine job offer related to your professional development",
          "Meeting the current age range for your country's agreement",
          "No criminal or medical inadmissibility concerns",
        ],
        process: [
          { title: "Job Offer Review", text: "We review the job offer to confirm it fits the Young Professionals criteria." },
          { title: "Profile Creation", text: "A pool profile is created referencing the job offer." },
          { title: "Invitation to Apply", text: "Selected profiles receive an invitation within a set window." },
          { title: "Application & Submission", text: "The work permit application is prepared and submitted with the job offer details." },
          { title: "Permit Issuance", text: "Once approved, the permit is issued for the named employer and role." },
        ],
        documents: ["Valid passport", "Signed job offer letter", "Proof of qualifications relevant to the role", "Passport photos"],
        commonIssues: ["A job offer that doesn't clearly show career development relevance", "Incomplete employer details on the offer letter", "Missing the invitation deadline"],
        howWeHelp: ["Review the job offer against program criteria", "Prepare a complete application package", "Coordinate timing with your employer"],
        faq: [
          { question: "Can I change employers under this permit?", answer: "Generally no — like other employer-specific permits, a change in employer usually requires a new application." },
          { question: "Does the job need to be full-time?", answer: "Requirements vary and should be checked against current program criteria for your country." },
        ],
        seoTitle: "IEC Young Professionals Program",
        seoDescription: "Guidance on the International Experience Canada Young Professionals category for job-offer-based professional work permits.",
      },
      {
        slug: "international-co-op",
        title: "International Co-op (Internship)",
        icon: "GraduationCap",
        image: "/images/services/temporary-residence_international-experience-canada_international-co-op.jpg",
        shortDescription: "A work permit for students completing an internship required by their academic program.",
        suitableFor: "Post-secondary students who need to complete an internship or co-op placement in Canada as part of their studies.",
        keyConsiderations: ["Internship must be required for your academic program", "Employer-specific work permit tied to the placement", "Usually shorter in duration than other IEC categories"],
        overview: [
          "The International Co-op category is designed for post-secondary students whose program requires an internship or work placement to graduate, and who have arranged that placement with a Canadian employer.",
          "It's employer- and placement-specific, reflecting the academic requirement behind it rather than general work experience.",
        ],
        eligibility: [
          "Enrollment in a post-secondary institution with an internship requirement",
          "A confirmed internship or co-op placement with a Canadian employer",
          "Citizenship of a partner country with this category open",
          "No criminal or medical inadmissibility concerns",
        ],
        process: [
          { title: "Placement Confirmation", text: "We confirm the internship is genuinely required by your academic program." },
          { title: "Profile Creation", text: "A pool profile is created referencing your placement details." },
          { title: "Invitation to Apply", text: "Selected profiles receive an invitation within a set window." },
          { title: "Application & Submission", text: "The work permit application is prepared with proof of the academic requirement and placement." },
          { title: "Permit Issuance", text: "Once approved, the permit is issued for the specific placement and employer." },
        ],
        documents: ["Valid passport", "Letter from your institution confirming the internship requirement", "Internship/placement agreement with the employer", "Passport photos"],
        commonIssues: ["Internships that aren't clearly tied to an academic requirement", "Missing confirmation letter from the institution", "Placement details that don't match the application"],
        howWeHelp: ["Confirm your placement meets program requirements", "Help obtain the right confirmation letter from your institution", "Prepare a complete, correctly timed application"],
        faq: [
          { question: "Can I do a voluntary internship under this category?", answer: "No — the internship generally needs to be a required part of your academic program, not an optional placement." },
          { question: "How long is the permit valid for?", answer: "Validity is generally tied to the length of the required placement, confirmed with your institution and employer." },
        ],
        seoTitle: "IEC International Co-op (Internship) Program",
        seoDescription: "Guidance on the International Experience Canada International Co-op category for academic internship placements in Canada.",
      },
    ],
  },
];
